README.md, SECURITY.md
Adds security policy to the repo
=> docs: added security policy

.snyk, README.md, package.json
add snyk protect (and badge) to patch 3 known vulnerabilities in `engine.io-client` and `engine.io`
=> feat: added snyk protect and badge

lib/index.js, package.json
It supports yaml config parsing in addition to js/json config parsing
`lib/index.js`
- `npm install` to install js-yaml
- copy and convert existing json config into yaml config
- `npm start` and observe the config being loaded
Commenting is allowed in yaml files which is a huge advantage over using json files.
#7 
N/A
N/A
=> feat: support yaml config

README.md
Fixes a broken link in the readme
=> chore: link in README.md

cli/init.js, lib/client/index.js, lib/client/socket.js, lib/filters/index.js, lib/index.js, lib/log.js, lib/relay.js, lib/server/index.js, lib/server/socket.js, lib/webserver.js, package.json
=> feat: add logging with bunyan

cli/init.js, lib/client/index.js, lib/client/socket.js, lib/filters/index.js, lib/healthcheck.js, lib/index.js, lib/log.js, lib/relay.js, lib/server/index.js, lib/server/socket.js, lib/webserver.js, package.json, test/functional/healthcheck.test.js
+ Adds the ability to get a client's health status by querying the server.
+ add logging with bunyan. Adds bunyan as a dependency and changes logging output format to json. removes most `debug` calls, and prints logs by default (used to require the --verbose flag)
=> add logging with bunyan, and a client-healthcheck endpoint to the server

client-templates/snyk/accept.json.sample
*IMPORTANT*: only to be merged after #28 
Adds maven support to the client template.
=> feat: add maven support to client template

client-templates/snyk/accept.json.sample
change client template to support nested .snyk policy files
=> feat: change client template to support nested .snyk policy files

client-templates/bitbucket-server/accept.json.sample, client-templates/github/accept.json.sample
Adds `package-lock.json` as an allowed file for filtering in GitHub commit webhooks and GET requests from repos.
=> feat: allow fetching package-lock.json to support npm5 projects

.travis.yml, dockerfiles/bitbucket-server/Dockerfile, dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile
Adds example `Dockerfile`s for generic use-cases:
- GitHub.com
- GitHub Enterprise
- Bitbucket Server
=> feat: dockerfiles

README.md, README.npm.md
Documents the dockerised usage of the snyk broker clients.
=> docs: dockerised readme

dockerfiles/bitbucket-server/Dockerfile, dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile
Fixes a typo in the Dockerfile healthcheck command.
=> fix: docker healthcheck proper command

.travis.yml
Stops triggering docker builds on PR tests in travis. Does so only on master branch pushes.
=> chore: dockerhub builds on master push only

README.md
=> docs: readme typos

README.md
Adds documentation on HTTPS, CA certs and custom accept filters to README.md.
=> docs: advanced configuration in readme

README.md, client-templates/gitlab/.env.sample, client-templates/gitlab/accept.json.sample, dockerfiles/gitlab/Dockerfile, lib/filters/index.js, lib/log.js, usage.txt
Add support for Gitlab servers.
=> feat: add support for gitlab

dockerfiles/gitlab/Dockerfile
Inits the gitlab docker image with default gitlab configuration.
=> fix: init gitlab settings for gitlab dockerfile

client-templates/gitlab/accept.json.sample, lib/filters/index.js
Add support to gitlab api V4 instead of V3 which has a project view limitations.
=> feat: support gitlab api v4 instead of v3

lib/relay.js, test/unit/relay-response-body.test.js, test/unit/relay-response-headers.test.js
Adds headers value substitution logic, following the same mechanism as body value substitution.
Must be merged and deployed before https://github.com/snyk/gitlab-agent/pull/21
=> feat: allow header values substition

README.md
Suggests to use `--restart=always` when running the docker container.
=> docs: docker restart policy recommended for reliability

README.md
Prominently suggests to pull the proper docker image in the readme :)
=> docs: docker pull instructions in readme.md

README.md
Add a mention of BROKER_CLIENT_URL for GitLab in the documentation (README.md)
=> docs: add BROKER_CLIENT_URL to gitlab docs

README.md
Add an example for building a Docker image for GitLab brokered support.
=> docs: GitLab example for the derived Docker image

client-templates/bitbucket-server/accept.json.sample
A fix to three incoming accept rules for bitbucket-server API endpoints.
=> fix: correct rules for webhook API endpoints

README.md
Updates the badge to test the repo instead of the npm published package.
=> docs: Snyk badge on GH repo

.snyk
Extends ignored vulns in Snyk policy.
=> chore: extend snyk policy ignores

lib/log.js, package.json
sanitizes headers when they are logged, to prevent unwanted data leakage.
=> feat: sanitize headers when logged

client-templates/github/accept.json.sample, test/fixtures/relay.json
uses a stricter regex for the graphql body regex filter.
=> fix: stricter regex for graphql

README.md, dockerfiles/bitbucket-server/Dockerfile, dockerfiles/gitlab/Dockerfile
To facilitate incoming webhooks, update the Gitlab and Bitbucket Server docks
=> doc: add BROKER_CLIENT_URL to Bitbucket Server and Gitlab

client-templates/bitbucket-server/accept.json.sample
Adds the ability to query bitbucket-server for open pull requests by branch.
See https://docs.atlassian.com/DAC/rest/stash/3.11.6/stash-rest.html#idp3175552 for the exact [GET] api endpoint.
=> feat: add the ability to query bitbucket-server for open prs by branch

client-templates/github/accept.json.sample
Github: Adds endpoints for webhooks with IDs, GET branch and user info.
=> feat: add an endpoint for webhooks with ids, get branch data, get user data

client-templates/github/.env.sample
fixes broken graphql endpoint for broker
- remove env existing variable for GITHUB_GRAPHQL and redeploy broker client.
- on snyk import a new project with nested target files and see that all are found.
=> fix: graphql url was configured wrong

.snyk
Updates vuln policy to ignore new vulns
=> chore: update ignore policy

README.md, dockerfiles/github-enterprise/Dockerfile
=> fix: ghe docker documentation

README.md
Correcting terminology around internal certificates.
=> docs: update reference to internal cert

client-templates/github/accept.json.sample
Used for future Snyk "add projects" improvements, and to facilitate seamless update and migration of Snyk pull-request checks
=> feat: allow iteration of all branches on a github repo

client-templates/github/accept.json.sample
Adds Gradle and SBT accept filters to GitHub sample
=> fix: add Gradle and SBT accept filters to GitHub sample

dockerfiles/jira/Dockerfile
Add a dockerfile for the jira broker flow
=> feat: add jira dockerfile

client-templates/jira/accept.json.sample
add servcerinfo endpoint for jira
=> feat: add servcerinfo endpoint for jira

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
Updating the PR template to reflect changes that have happened recently:
- PR reviews are handled by GitHub directly now
- Angular-style docs moved
- Link to CONTRIBUTING.md file
=> chore: update pull request template to reflect changes

README.md, README.npm.md
Adds information about configuring the port, and the healthcheck of the broker.
=> docs: document port and healthcheck configuration

README.md, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample
Adds additional rules to allow the use of `user/orgs`
=> feat: adds user/orgs rule

cli/exec.js, cli/init.js, lib/client/index.js, lib/client/socket.js, lib/filters/index.js, lib/relay.js, lib/server/index.js, lib/server/socket.js, lib/webserver.js, package-lock.json, package.json
* Adds logging in case of websocket close and error events for debug purposes.
* Removing `debug` dependency, relying solely on `bunyan` for logging.
* Logging *masked* tokens for improved traceability in logs without exposing sensitive data.
* Robust logging when relaying requests (HTTP- and WS-originated)
* Log on incoming request
* Log on block by filters
* Log on relay
* Log on relay response
=> fix: stronger observability through logging

client-templates/bitbucket-server/accept.json.sample, client-templates/gitlab/accept.json.sample
part of broker's Hierarchical and paginated requests, added broker support for BB and GL
=> feat: adding support for paginated list

client-templates/bitbucket-server/accept.json.sample
=> feat: add code insights paths

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample
Adds the necessary rules for GH & GHE needed for the new projects at scale functionality where we will make more efficient queries for fetching repos to import.
=> feat: add GH & GHE rules for listing org & user repos

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample
adding support for github.com and github-enterprise for the search repositories endpoint
=> feat: add gh search api to accept

client-templates/bitbucket-server/accept.json.sample
As part of adding support for PAS. we added some API endpoints to BB.
BB accept template updated to support such api calls.
=> feat: add bb search api to accept

README.md
Updates formatting of the GitLab wordmark to align with their brand guidelines:
https://about.gitlab.com/handbook/marketing/corporate-marketing/#word-list
=> chore: adjust captilization of GitLab

package-lock.json, package.json
Updates dependency snyk-config to the latest version
=> fix: bump config dep

client-templates/github-enterprise/accept.json.sample, lintVerifier.sh, package.json
Added a JSON verifier to make sure accept.json.sample files are valid during the build process
=> fix: add the json verifier to avoid typo errors in json template files

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
Add support of `composer.lock` and `composer.json` files
[BST-693](https://snyksec.atlassian.net/browse/BST-693)
=> feat: add composer files support

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
Add support for `project.assets.json` file
[BST-705](https://snyksec.atlassian.net/browse/BST-705)
=> feat: add project.assets.json support

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample
add /git/trees endpoint to GitHub and GitHub Enterprise accept.json.sample to support recursive manifest search in a repository
https://snyksec.atlassian.net/browse/COMET-243
=> Allow fetching list of all files for GitHub and GHE

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, test/fixtures/client/github/graphql/find-pull-requests-closed.txt, test/fixtures/client/github/graphql/find-pull-requests-invalid-query.txt, test/fixtures/client/github/graphql/find-pull-requests-open.txt, test/fixtures/relay.json, test/unit/filters.test.js
Support find open pull requests for auto dep upgrades prs
=> feat: support find open pull requests for auto dep upgrades prs

package-lock.json, package.json
upgrade snyk-config (after it's lodash version has been updated, due to a vuln). instead of https://github.com/snyk/broker/pull/182/files
=> fix: upgrade snyk-config to 2.2.3

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample
https://snyksec.atlassian.net/browse/COMET-277
=> feat: allow API for counting contributing developers

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
Add support for python custom manifest filenames.
=> feat: add support for python custom filenames

lib/relay.js, test/functional/server-client.test.js
Fixes the log text that I broke today 😄
=> fix: websocket response log

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
- update accept rules to allow `Podfile` and `Podfile.lock`
=> feat: Add support for CocoaPods

client-templates/github-enterprise/accept.json.sample
- Fixes a typo in GHE accept rules
=> fix: Fix GitHub Enterprise Accept rules sample

.travis.yml, lintVerifier.sh
Applies linting to sample accept filters on CI. Will help us release proper accept filters!
=> chore: lint accept filters on CI

client-templates/artifactory-cr/.env.sample, client-templates/artifactory-cr/accept.json.sample, dockerfiles/artifactory-cr/Dockerfile
This PR adds the client templates for Artifactory Container Registry
=> fix: Adding client templates for Artifactory Container Registry

README.md
This PR adds the configuration for Artifactory CR to the README.
=> fix: Add Artifactory configuration to README

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample
Fix rule to pass requests to [get single commit GitHub API](https://developer.github.com/v3/repos/commits/#get-a-single-commit).
=> fix: get commit data rule

README.md
Based on customer feedback + Style Guide decisions (Git instead of SCM) + after reviewing content in parallel with improvments to the main Broker docs. Additional changes will be suggested as further decisions are made re: the Broker and/or Style Guide.
=> fix: Various fixes to README.md

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
Add access to the necessary Cloud Config files using the `accept.json` (yaml, yml, json)
=> feat: add Cloud Config support to the accept.json.sample

README.md, README.npm.md, client-templates/artifactory/.env.sample, client-templates/artifactory/accept.json.sample, dockerfiles/artifactory/Dockerfile
Create set up for private artifactories
- .env and accept.json samples
- Dockerimage
=> feat: create set up for private artifactories

README.md
Fix URL for artifactory integration in README
=> fix: URL for artifactory integration in README

README.md, client-templates/artifactory/.env.sample, dockerfiles/artifactory/Dockerfile
=> chore: fix ARTIFACTORY_URL

client-templates/github-com/accept.json.sample
Adds whitelist sample rules to allow manifests and snyk files to be updated via the GitHub Contents API.
=> feat: update GitHub whitelist sample for writing via Contents API

client-templates/gitlab/accept.json.sample
Adds whitelist sample rules to allow manifests and snyk files to be updated via the Gitlab Repository Files API.
=> feat: add whitelist entries for Gitlab Repository Files API

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample
Removes the unneeded API whitelisting for the Repository Tree and Commits APIs.
Updates GitHub Enterprise whitelist to match GitHub.
=> fix: remove unneeded whitelist entries for GH and make GHE match

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
Allow pip files that match pattern `requirements/*.txt` through
=> feat: allow requirements/*.txt for pip projects

SECURITY.md
Adds disclosure of known broker vulnerabilities.
=> chore: add known vulnerabilities to SECURITY

SECURITY.md
Updates known vulnerabilities links to point at the Snyk Vulnerability DB on https://snyk.io/
=> chore: update known vulns to point at snyk DB

cli/init.js
This patch modernises the format of the CLI init code, dropping its usage of `then-fs` in the process. Overall we've moved from Promise chains to async..await, and renamed many variables to make the flow more understandable
Tests have not been touched to gain confidence that the code functions the same as before
Co-Authored-By: Ohad Finkelstein <ohad.finkelstein@snyk.io>
=> feat: modernise cli init code

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
Adds support for Dockerfile scanning through brokered integrations for configuring Dockerfile path for images imported through Docker Hub, ECR, GCR, ACR and Artifactory CR.
=> feat: accept Dockerfile response

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample
Adds pull-request assignment endpoint to broker accepted endpoints.
=> feat: add pull-request assignment endpoint to accepted ones

lib/server/index.js
Following #276 - adding a `fix` PR to trigger a semantic release process so we could roll this change out
=> fix: metric comment

README.md, client-templates/azure-repos/.env.sample, client-templates/azure-repos/accept.json.sample, dockerfiles/azure-repos/Dockerfile, lib/auth-header.js, lib/log.js, test/unit/log.test.ts
Adding support of Azure Repos integration.
New files:
- client-templates/azure-repos/.env.sample - template of required settings for run broker client
- client-templates/azure-repos/accept.json.sample - whitelist template of required Azure API endpoints
- dockerfiles/azure-repos/Dockerfile - Dockerfile template
Additional changes:
- adds Azure Repos to sanitisation logic
=> feat: Azure Repos support

lib/server/index.js
Add basic prometheus metrics (not including paths)
=> feat: add basic prometheus metrics

README.md
=> chore: fixed small typo error

README.md
=> chore: enabled syntax highlighting

README.md, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample
A new section that contains some useful workarounds to tackle issues.
This PR adding additional rules to handle Fix PR failures for GitHub / GitHub Enterprise users,
when the root cause is fetch big (> 1MB) manifest file failure
=> feat: added troubleshooting section

client-templates/artifactory/.env.sample
change example artifactory url from one with snyk in it to generic one
=> chore: change example artifactory url

package.json
=> chore: update snyk-config to prerelease v4

README.md
Empty PR to trigger image rebuild and pick latest base image updates (nodejs version upgrade - security fixes)
=> fix: rebuild docker images

lib/patch-https-request-for-proxying.js
This PR handles the proper env vars for a proxy used in broker client, and basically adds the support for any proxy authentication in broker.
=> feat: support proxy authentication

client-templates/artifactory/.env.sample
Enhance `/systemcheck` endpoint of Artifactory broker client with `/api/system/ping`. It will help us narrow down connectivity problems
=> feat: add artifactory endpoint for system check

client-templates/azure-repos/accept.json.sample, client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
Adds `go.mod` and `go.sum` to github sample file
=> feat: add go.mod and go.sum manifest to github

README.md, client-templates/container-registry-agent/.env.sample
This PR updates CR_AGENT_URL env variable docs for the container registry agent broker client
=> docs: Update CR_AGENT_URL env variable docs

client-templates/azure-repos/.env.sample
Added missed configuration of `/systemcheck` endpoint for Azure broker client
=> fix: add /systemcheck endpoint

README.md
Updates the README.md file to include the AZURE_REPOS_HOST.
=> docs: update readme with AZURE_REPOS_HOST

client-templates/container-registry-agent/accept.json.sample
Adds missing endpoints required for the container brokered solution
=> fix: add endpoints for scan callbacks v1

lib/log.js, lib/relay.js, lib/server/index.js, lib/server/socket.js, lib/token.js
This PR makes some logging improvements on the broker-server:
* masked token is included in every request
* header.X-Broker-Token is removed
=> feat: Log maskedToken on every server request

dockerfiles/ubuntu/Dockerfile
- Updates the node version to fix some vulnerabilities found in the earlier version
- Updates the key servers, sks-keyservers.net is no longer available
=> feat: update the node version for security

README.md
- [x ] Ready for review
Update broker proxy config based on https://snyk.zendesk.com/agent/tickets/11062
One file changed, only changed docs/text. 
Review text changes for accuracy.
=> docs: Add proxy config based on docs_needed ticket 11062.

lib/index.js, package.json
Installing and running this is causing issues in some envs. Removing for now, might put it back later if the package has less requeriments.
=> feat: remove node-dump-stacks

README.md
Updates container registry agent docs to be consistent with https://support.snyk.io/hc/en-us/articles/360017040957-Snyk-integration-to-self-hosted-container-registries
=> docs: update container registry agent environment variables

dockerfiles/ubuntu/Dockerfile
- Upgrade node (patch level 12.22.3->12.22.5) to address Snyk vulnerabilities
=> fix: node 12.22.3->12.22.5, addresses Snyk vulnerabilities

dockerfiles/ubuntu/Dockerfile
this PR fixes the ubuntu vulns introduced in 20.10
=> fix: ubuntu vulns

.circleci/config.yml
Upgrade circleci pipeline to node 14
=> chore: upgrade circleci pipeline to node 14

package.json
this PR bumps request package in order to update the high vuln fix of jsonschema (see [here](https://github.com/joyent/node-jsprim/issues/33))
more context [here](https://snyk.slack.com/archives/C02GCNHTUAU/p1638449675115700)
=> fix: bump request to update the fixed high vuln of jsonschema

lib/server/index.js
Server healthcheck on root  path `/`
=> feat: server healthcheck on root path

bin/container-registry-agent/docker-entrypoint.sh, dockerfiles/container-registry-agent/Dockerfile
Use Alpine for container registry agent to reduce the image size.
=> fix: use alpine for container registry agent

client-templates/azure-repos/accept.json.sample
This PR adds accept rule for file existence in azure repos.  This accept rule is needed for the open fix PR flow in Azure Repos.
This fix is done as part of adding support for fix PRs of hidden files and folders.
A preliminary step for this PR is to allow importing hidden dockerfiles for azure repos: https://github.com/snyk/broker/pull/384
=> feat: Allow check file existence in Azure Repos

client-templates/nexus/.env.sample
Remove '/repository' from the NEXUS_URL, as we need to be able to access both '/repository' and '/service'.
=> fix: nexus base URL

lib/auth-header.js
Enables the possibility for broker client to use bearer tokens for auth.
Resolves: https://github.com/snyk/broker/issues/396
=> feat: Add 'bearer' auth scheme

lib/client/socket.js, lib/server/socket.js
This PR adds config entries for `primus` configuration, and is intended to assist with testing streaming for LCE.
Related to: https://snyksec.atlassian.net/browse/NEBULA-499
=> feat: add config for primus websockets

lib/client/socket.js, lib/relay.js, lib/server/socket.js
parseInt(undefined) = NaN
NaN ?? 1000 = NaN
Therefore use || as the fallback operator
=> fix: remove use of ?? for config values

dockerfiles/artifactory/Dockerfile, dockerfiles/azure-repos/Dockerfile, dockerfiles/bitbucket-server/Dockerfile, dockerfiles/container-registry-agent/Dockerfile, dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile, dockerfiles/gitlab/Dockerfile, dockerfiles/jira/Dockerfile, dockerfiles/nexus/Dockerfile, dockerfiles/ubuntu/Dockerfile
Update to a more recent version of Ubuntu and Node to take advantage of the latest security updates.
=> feat: update Ubuntu, node and npm versions

client-templates/nexus2/.env.sample, client-templates/nexus2/accept.json.sample, dockerfiles/nexus2/Dockerfile
- Update `BROKER_CLIENT_VALIDATION_URL` for `nexus` `.env.sample`
- Create Nexus 2 client-templates and dockerfile (`nexus2`). `nexus` will refer to Nexus 3 as before
- Changing accept.json method 'any' on `NEXUS_URL` to `GET` to be more specific on what Snyk requires access to, for `nexus` and `nexus2`
- The [README will be updated for Nexus 3 ](https://github.com/snyk/broker/pull/417) but only merged before GA. Nexus 2 will be going into beta so not for now.
=> feat: add Nexus 2 client-templates and dockerfile & update Nexus 3 BROKER_CLIENT_VALIDATION_URL

client-templates/nexus2/.env.sample
- adds a small comment on `nexus2` `.env.sample`
- already merged https://github.com/snyk/broker/pull/412 which is `nexus2` client templates / Dockerfile
- this will help trigger build on Docker Hub (now that build tiggers have been added)
=> chore: add comment on nexus2 .env.sample

README.md
- Updates the `README.md` for Nexus 3 GA (will not be merged until then)
- WILL NOT BE MERGED UNTIL NEXUS 3 INTEGRATION IS GA
- Nexus 3 has been in beta and will be in GA soon
- Orginal work added in #382
=> docs: update README.md for Nexus 3

dockerfiles/container-registry-agent/Dockerfile
Update the base image of the container registry agent broker to align with the base image we use for the container-registry-agent, to fix high severity vuln.
=> chore: update cra broker base image to alpine to 3.16

dockerfiles/ubuntu/Dockerfile
Update to a more recent version of Node to take advantage of the latest security updates. This should also include some updates in the base image.
=> feat: Update node version in snyk/ubuntu

README.md
=> chore: add docs for changing auth method

README.md
Triggers a release because I've fumbled a commit message in the [previous PR](https://github.com/snyk/broker/pull/437) after rebase-renaming ._.
N/A
N/A
N/A
N/A
N/A
=> feat: trigger release

README.md
Commit string was incorrect in previous commit and didn't trigger a release. Making a dummy commit to do that now.
=> feat: trigger a release

README.md
Fixes typo and triggers release
=> fix: fix typo and trigger release

dockerfiles/ubuntu/Dockerfile
- Update node version for base image
=> fix: Update node version for ubuntu base image

lib/filter-rules-loading.js, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap, test/unit/runtime-rules-hotloading.test.ts
Adds missing rules in the [Snyk CODE specific accept rules](https://docs.snyk.io/features/snyk-broker/snyk-broker-code-agent/setting-up-the-code-agent-broker-client-deployment/step-5-setting-up-the-broker-client/step-5.2b-running-the-broker-client-with-the-code-snippets-display#downloading-the-accept.json-file) injection mechanism, to support code snippet viewing in the project view.
=> fix: add missing code snippets injected rules for code

.circleci/config.yml, .gitignore, package.json
=> Build binary artifact in CI

client-templates/container-registry-agent/accept.json.sample
- chore: format container registry agent accept json
=> chore: format container registry agent accept json

client-templates/container-registry-agent/accept.json.sample
- add container registry agent callback URL
- CIT-485
=> [CIT-485] feat: add container registry agent callback url

client-templates/container-registry-agent/accept.json.sample
Remove unused path rules for container registry agent accept json
=> fix: update container registry agent accept json

.circleci/config.yml, client-templates/github-server-app/.env.sample, client-templates/github-server-app/accept.json.sample, config.default.json
Adds `accept.json` rules for GitHub Server App.
[Jira TREX-636](https://snyksec.atlassian.net/browse/TREX-636)
=> feat: add client templated for github-server app

lib/server/routesHandlers/postResponseHandler.ts
=> fix: align logging ctx member to the rest of logs [HYB-231]

.circleci/config.yml, .gitignore, .npmrc, dockerfiles/Dockerfile.dev, package-lock.json, package.json
This PR introduces `package-lock.json`. This will ensure that exact, versioned dependency tree is used by building/publishing our package.
Additionally, `tough-cookie` dependency is removed from dev Dockerfile (it was forgotten in https://github.com/snyk/broker/pull/700).
=> feat: introduce package lock file [HYB-123]

lib/common/http/webserver.ts, package-lock.json
- [] Ready for review
- Bumps deps versions (relock)
- Increase server webserver keepalive to be higher than proxy to avoid ECONNRESETs
=> fix: increase server webserver keepalive value [HYB-465]

lib/common/http/downstream-post-stream-to-server.ts
Improves the connection handling and garbage collection for requests made by client.
Closing the connection allows for request garbage collection, avoiding memory leaks due to long keepalive keeping resources used.
Further improvements will attempt keeping the TCP connection going for separate http requests.
Let manually destroying and cleaner finishing instead.
=> fix: cleaner data POST streaming conn handling [HYB-465]

.gitleaks.toml, config.default.json, defaultFilters/apprisk.json, lib/client/types/config.ts, lib/client/utils/connectionValidation.ts
adding Checkmarx rules too apprisk config
=> feat: add checkmarks rules

.circleci/config.yml, dockerfiles/Dockerfile-universal.ubi
=> fix: add universal broker docker images

.circleci/config.yml, lib/server/socketHandlers/closeHandler.ts
Improves closing handler to be more robust and avoid crashes in the weird scenarios where there is no token in pool somehow.
=> fix: avoid closing crashes when no conn in pool somehow [HYB-186]

.circleci/config.yml
Removes approval step for universal images and aligns jobs properly.
=> fix: rm approval for universal images [HYB-261]

lib/common/config/config.ts, lib/common/config/universal.ts, test/unit/relay-response-body-universal.test.ts
Interpolates reflected config values in given connection for universal broker.
=> fix: interpolate reflected cfg values

.gitleaks.toml, config.default.json, defaultFilters/apprisk.json, lib/client/types/config.ts, lib/client/utils/connectionValidation.ts, lib/common/relay/prepareRequest.ts, test/unit/relay-response-body-form-url-encoded.test.ts, test/unit/relay-response-body-universal-form-url-encoded.test.ts, test/unit/relay-response-headers-form-url-headers.test.ts, test/unit/relay-response-headers-universal-form-url-headers.test.ts
Adds basic skeleton for AppRisk flavor + rules in universal broker.
=> feat: add AppRisk flavor skeleton [HYB-463]

client-templates/artifactory/accept.json.sample, client-templates/nexus/accept.json.sample, client-templates/nexus2/accept.json.sample, defaultFilters/artifactory.json, defaultFilters/nexus.json, defaultFilters/nexus2.json
Removes unnecessary filter rules for private package registries.
=> fix: update private pkg registries filters

lib/server/socketHandlers/closeHandler.ts
Fixes unhandled exception if client is undefined.
=> fix: avoid crash on closehandler

lib/common/http/downstream-post-stream-to-server.ts
Increases client timeout (1200s) with timeout value override logic available.
=> fix: increase timeout value for POST data [HYB-465]

lib/client/dispatcher/index.ts, lib/client/hooks/startup/processHooks.ts, lib/client/index.ts, lib/client/socket.ts, lib/client/socketHandlers/openHandler.ts, lib/client/types/client.ts, lib/client/utils/configHelpers.ts, lib/server/utils/socket.ts, test/functional/server-client.test.ts, test/unit/configHelper.test.ts
Adds some broker client configuration metadata to be shared with the server for better supportability.
=> feat: send clientconfig metadata to server [HYB-202]

defaultFilters/apprisk/gitlab.json, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap
Add the Gitlab metadata endpoint for AppRisk Gitlab.
=> fix: add gitlab metadata endpoint

lib/client/index.ts, lib/server/index.ts
Makes a trace more explicit and trigger release following contribution.
=> fix: Adjusting traces and trigger release

config.universaltest.json, lib/client/auth/oauth.ts, lib/client/index.ts, lib/client/socket.ts, lib/client/types/client.ts, lib/client/types/config.ts, lib/common/types/options.ts, lib/server/socket.ts, test/functional/client-universal-server.test.ts, test/functional/healthcheck-universal.test.ts, test/functional/server-client-universal.test.ts, test/functional/systemcheck-universal.test.ts, test/unit/config.test.ts, test/unit/relay-response-body-form-url-encoded.test.ts, test/unit/relay-response-body-universal-form-url-encoded.test.ts, test/unit/relay-response-body-universal.test.ts, test/unit/relay-response-body.test.ts, test/unit/relay-response-headers-form-url-headers.test.ts, test/unit/relay-response-headers-universal-form-url-headers.test.ts, test/unit/relay-response-headers-universal.test.ts, test/unit/relay-response-headers.test.ts
Adds oauth cred retrieval upon startup for clients.
=> feat: add jwt retrieval logic

defaultFilters/apprisk/bitbucket-server.json, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap
Adds a new accept route for AppRisk
N/A
I don't have access to a bitbucket server to manually test this.  This accept is entirely based on the code and the log files, but since it's relatively simple I'm confident it should work.
N/A
N/A
N/A
=> feat: add apprisk catalog-info.yaml accept

.circleci/config.yml, client-templates/bitbucket-server-bearer-auth/.env.sample, client-templates/bitbucket-server-bearer-auth/accept.json.sample, config.default.json, defaultFilters/apprisk/bitbucket-server-bearer-auth.json, defaultFilters/bitbucket-server-bearer-auth.json
Adds bearer auth scheme flavor for bitbucket server no longer using basic auth.
=> feat: add bitbucket server bearer auth flavor [HYB-519]

lib/server/socket.ts
Removes placeholder code temporarily for broker server upgrade, until ready to bring it back in.
=> fix: rm server side ws auth function till ready [HYB-524]

lib/server/routesHandlers/httpRequestHandler.ts, package-lock.json, package.json, test/unit/no-client-for-token.test.ts, test/unit/old-client-redirect.test.ts
Requests for connection without tunnels in secondary pods redirect to primary pods.
=> fix: single conn client secondry redirects to primary

lib/server/routesHandlers/httpRequestHandler.ts, package-lock.json, package.json, test/unit/old-client-redirect.test.ts
Makes the request from the secondary for older clients instead of issuing a redirect.
=> fix: make request from secondry instead of redirect [HYB-512]

dockerfiles/base/Dockerfile.ubi
Remove glibc unused yet marked as vulnerable package.
=> fix: rm glibc package with vuln

lib/client/checks/config/brokerClientVersionCheck.ts, lib/client/checks/config/index.ts, test/unit/client/checks/config/brokerClientVersionCheck.test.ts, test/unit/client/checks/config/brokerClientVersionSkipDevLocalVersionCheck.test.ts
Checks the broker client version to be kept up to date.
=> feat: add broker client version preflight check

lib/server/routesHandlers/httpRequestHandler.ts, test/unit/old-client-redirect.test.ts
[Server only] Fixing the uri targeted by the secondary pods.
=> fix: primary endpoint uri rewrite

lib/client/brokerClientPlugins/plugins/githubServerAppAuth.ts, test/unit/plugins/brokerPlugins/github-server-app.test.ts
Adds checks to verify that the github-server-app plugin has what it needs to function.
=> fix: add tighter validation in github-srv-app plugin [HYB-542]

defaultFilters/github-server-app.json, lib/client/brokerClientPlugins/pluginManager.ts, lib/client/brokerClientPlugins/plugins/githubServerAppAuth.ts, lib/client/index.ts, lib/common/config/config.ts, test/unit/plugins/brokerPlugins/github-server-app.test.ts
Fixes the github server app plugin to generate jwt correctly.
Also fixes plugins loading in images.
=> fix: [unibroker] github srv app plgn and plugins loading

config.default.json, defaultFilters/workload.json
Adds workload connection type for upcoming hybrid platform.
=> feat: add workload connection type [HYB-574]

config.default.json, defaultFilters/github-server-app.json
This PR updates the github-server-app default filters:
* Adds missing AuthN (`Bearer ACCESS_TOKEN`)).
* Adds missing call to list installations for app (using a `Bearer JWT_TOKEN`).
* Removes calls that are not made by the integration type.
This is not yet ready for testing, see Slack thread in team channel.
=> feat: GitHub Server App default filters

.snyk
- Ignore WS vuln for another month
=> chore: extend ignore for SNYK-JS-WS-7266574

defaultFilters/github-server-app.json
Update webhook path, should use `/webhook/github-server-app` for the app.
=> chore: update webhook path for github-server-app

lib/common/config/config.ts, lib/common/filter/filter-rules-loading.ts, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap, test/unit/runtime-rules-hotloading.test.ts
Adds git cloning rules for ghsa integration in universal broker.
=> chore: add accept git rules for ghsa

lib/client/types/api.ts
Aligns type to platform for universal broker
=> chore: [unibroker] tiny type adjust

lib/client/brokerClientPlugins/plugins/githubServerAppAuth.ts, lib/common/utils/token.ts
Adds some error handling in ghsa plugin.
=> chore: add ghsa plugin error handling

lib/client/brokerClientPlugins/plugins/githubServerAppAuth.ts, test/unit/plugins/brokerPlugins/github-server-app.test.ts
Fixes token renewal process for Github Server App plugin in universal Broker.
=> chore: fix ghsa tokens renewals

lib/common/relay/forwardWebsocketRequest.ts
fixes debug mode header logging.
=> fix: restore headers in debug logcontext

config.default.json, defaultFilters/github-server-app.json, lib/client/brokerClientPlugins/abstractBrokerPlugin.ts, lib/client/brokerClientPlugins/pluginManager.ts, lib/client/brokerClientPlugins/plugins/githubServerAppAuth.ts, lib/common/config/pluginsConfig.ts, lib/common/config/universal.ts, lib/common/filter/filter-rules-loading.ts, test/unit/plugins/brokerPlugins/github-server-app.test.ts
[Only applies to universal broker]
Fixes github server app plugins credential management
and add url var interpolation for github server app.
=> fix: ghsa short lived creds mngt and url var swap

lib/common/filter/filter-rules-loading.ts, test/unit/runtime-rules-hotloading.test.ts
Fixes the code snippet rule in universal broker for GHSA to ensure right auth scheme.
=> fix: code snippet rule injection for ghsa

config.default.json, defaultFilters/github-cloud-app.json, defaultFilters/github-server-app.json, lib/client/brokerClientPlugins/plugins/githubServerAppAuth.ts, lib/common/filter/filter-rules-loading.ts, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap, test/unit/plugins/brokerPlugins/github-server-app.test.ts, test/unit/runtime-rules-hotloading.test.ts
Extends support for github cloud app integration.
=> feat: add ghca support [HYB-605]

.snyk
Extends the mitigated WS vuln till feb 2025.
https://github.com/snyk/broker/pull/787
=> chore: ignore mitigated ws vuln

SECURITY.md
Adds note about mitigated WS vuln and trigger release.
=> fix: add ws mitigated vuln info in security.md

config.default.json, defaultFilters/apprisk.json
Adds sonarqube support to AppRisk connection type.
=> feat: add sonarqube to apprisk connection type [IA-573]

defaultFilters/apprisk/azure-repos.json, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap
=> chore(azure apprisk): update apprisk rules

lib/client/config/configHelpers.ts, lib/client/config/remoteConfig.ts, lib/client/index.ts, lib/client/types/client.ts, test/functional/server-client.test.ts, test/unit/configHelper.test.ts, test/unit/connectionsManager/manager.test.ts
Adds some broker client identifying data for observability.
=> chore: [unibroker] add client id data on conn sync calls

lib/common/filter/filter-rules-loading.ts, test/unit/runtime-rules-hotloading.test.ts
- Allows snippets to be disabled with `DISABLE_SNIPPETS` env var
=> chore: allow snippets rules to be disabled

package-lock.json, package.json
=> chore: axios upgrade

client-templates/azure-repos/accept.json.sample, defaultFilters/azure-repos.json, test/fixtures/accept/azure-repos.json, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap, test/unit/filters.test.ts
Adds support for the permission evaluation endpoint through the broker.
=> chore: add permission evaluation endpoint for azure [SCM-502]

defaultFilters/apprisk.json
https://snyksec.atlassian.net/browse/IA-566
Add bearer authentication to sonarqube and add `/projects/search` endpoint
=> Fix sonarqube apprisk connection type

client-templates/gitlab/accept.json.sample, defaultFilters/gitlab.json, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap, test/unit/filters.test.ts
Adds `/api/v4/personal_access_tokens/self` endpoint support for gitlab which will be used to check properly check token has the needed scopes when validating credentials.
=> chore: add get self access token rule for gitlab [SCM-503]

lib/common/filter/filter-rules-loading.ts, test/unit/runtime-rules-hotloading.test.ts
- Modifies behaviour of `DISABLE_SNIPPETS` to ensure appropriate scm-specific rules are set
- Improves tests to assert setting of paths
=> fix: disable snippets logic

.circleci/config.yml, .releaserc
Adds SBOM generation to release process.
=> chore: add sboms to release process [HYB-710]

lib/server/index.ts, package-lock.json, package.json
- Adds `node-dump-stacks` to the server component of Broker
- Identify occurrences where the event loop becomes blocked
=> chore: node-dump-stacks [HYB-717]

client-templates/apprisk/.env.sample, client-templates/apprisk/accept.json.sample
Adds missing template for apprisk image building in classic broker.
=> fix: add apprisk rules for classic broker template

lib/server/index.ts, package-lock.json, package.json
Remove problematic dependency to fix image building.
=> fix: rm node dump stack dep

package-lock.json, package.json
This PR pins `@types/express` to version 4.17.21 and makes TS types happy.
=> chore: pin @types/express to 4.17.21

.circleci/config.yml
This PR adds two steps to CICD workflow: building Docker images (Ubuntu and RHEL based). This will help to catch any issues related to building Docker images earlier and not by releases.
=> chore(circleci): build base images by CICD workflow

.snyk
This PR ignores `cross-spawn` vuln temporary.
=> fix: ignore cross-spawn vulnerability temporary

client-templates/azure-repos/accept.json.sample, client-templates/bitbucket-server-bearer-auth/accept.json.sample, client-templates/bitbucket-server/accept.json.sample, client-templates/gitlab/accept.json.sample, defaultFilters/azure-repos.json, defaultFilters/bitbucket-server-bearer-auth.json, defaultFilters/bitbucket-server.json, defaultFilters/gitlab.json, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap, test/unit/filters.test.ts
Adds filter exceptions for the /pull-request endpoints added to the BBS, Azure and Gitlab agents.
=> feat: add new client endpoint filters

client-templates/bitbucket-server-bearer-auth/accept.json.sample, client-templates/bitbucket-server/accept.json.sample, defaultFilters/bitbucket-server-bearer-auth.json, defaultFilters/bitbucket-server.json, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap, test/unit/filters.test.ts
Adds rules for bitbucket server inline comments and comment resolution
JIRA Issue: https://snyksec.atlassian.net/browse/TREX-1513
=> feat: Add bitbucket server inline comment and resolution

dockerfiles/Dockerfile-universal, dockerfiles/Dockerfile-universal.dev, dockerfiles/Dockerfile-universal.ubi
Enables universal broker logic in universal images.
=> fix: enable universal logic in universal imgs

lib/client/socket.ts, lib/hybrid-sdk/responseSenders.ts
Fixes a regression breaking the High availability mode for non universal broker.
=> fix: restore ha mode by adding serverId again post refactoring

lib/client/config/configHelpers.ts, lib/client/dispatcher/client/api.ts, lib/client/socket.ts, lib/hybrid-sdk/http/downstream-post-stream-to-server.ts
Adds auth headers everywhere needed.
=> fix: add auth headers on all flows [HYB-724]

package-lock.json
Bump express version to fix redos vuln in path-to-regexp.
=> fix: SNYK-JS-PATHTOREGEXP-8482416

lib/client/config/configHelpers.ts, lib/client/index.ts, test/functional/server-client.test.ts
Disable body logging, which causes excessive logging, crash for large data transfer, and is left on too often.
=> chore: disable body logging

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/github-server-app/accept.json.sample, defaultFilters/github-enterprise.json, defaultFilters/github-server-app.json, defaultFilters/github.json, test/fixtures/accept/github.json, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap, test/unit/filters.test.ts
Add github rules for updating webhook config
https://github.com/snyk/scm-agents/pull/629
=> feat: allow webhook update calls

client-templates/azure-repos/accept.json.sample, defaultFilters/azure-repos.json, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap, test/unit/filters.test.ts
Add azure rules to update webhooks
https://github.com/snyk/azure-repos-agent/pull/623
=> chore: add rules for azure update webhook [SCM-898]

lib/server/routesHandlers/connectionStatusHandler.ts, lib/server/routesHandlers/httpRequestHandler.ts, test/functional/server-client.test.ts
Adds clearer failure reason via header.
=> chore: add broker failure details via header

defaultFilters/apprisk/gitlab.json
add new endpoint to be whitelisted for apprisk ui
=> chore: add gitlab apprisk endpoint to whitelist

lib/broker-workload/index.ts, lib/broker-workload/prepareRequest.ts, lib/client/auth/oauth.ts, lib/client/brokerClientPlugins/abstractBrokerPlugin.ts, lib/client/brokerClientPlugins/pluginManager.ts, lib/client/brokerClientPlugins/plugins/githubServerAppAuth.ts, lib/client/checks/config/brokerClientVersionCheck.ts, lib/client/config/remoteConfig.ts, lib/client/dispatcher/client/api.ts, lib/client/utils/connectionValidation.ts, lib/common/filter/utils.ts, lib/hybrid-sdk/http/request.ts, lib/hybrid-sdk/requestsHelper.ts, lib/server/routesHandlers/connectionStatusHandler.ts, lib/server/routesHandlers/httpRequestHandler.ts, package-lock.json, package.json, test/fixtures/client/filters.json, test/functional/server-client.test.ts, test/setup/test-web-server.ts, test/unit/filters.test.ts, test/unit/plugins/pluginManager.test.ts, test/unit/utils.test.ts
Allows encoding headers through to benefits of compression as much as possible.
Was primarily disabled historically when the data responses were piped into the WS tunnel. No longer applicable.
=> fix: allow encoding headers through

defaultFilters/apprisk/azure-repos.json, defaultFilters/azure-repos.json, defaultFilters/customPrTemplates/azure-repos.json, lib/hybrid-sdk/common/filter/filter-rules-loading.ts, lib/hybrid-sdk/common/filter/utils.ts
Revert rules merging logic to keep things as simple as possible. Merging problematic essential rule into main ruleset.
=> chore: revert filters merging logic

config.default.json, config.universaltest8.json, lib/hybrid-sdk/client/utils/connectionValidation.ts, lib/logs/logger.ts, test/functional/systemcheck-universal.test.ts
This PR ensures that all URLs are sanitised in validations responses by systemcheck.
=> fix: sanitise urls in systemcheck validations

.snyk, lib/hybrid-sdk/client/checks/config/workloadConfiguration.ts, lib/hybrid-sdk/common/config/config.ts
=> fix: workload preflight check

catalog-info.yaml, dockerfiles/base/Dockerfile, dockerfiles/base/Dockerfile.ubi
=> chore: update team name to hybrid

lib/hybrid-sdk/common/utils/token.ts, test/unit/token.test.ts
Improves logs sanitization server side
=> chore: improve token sanitization

defaultFilters/apprisk/azure-repos.json
https://snyksec.atlassian.net/browse/APRSK-763
Adds rule for GET in addition to the existing OPTIONS rules
=> chore: add azure GET rules for language endpoints

package-lock.json, package.json
This PR upgrades express package to version `4.21.2`.
=> fix(deps): upgrade express to 4.21.2

lib/hybrid-sdk/server/socketHandlers/connectionHandler.ts
Ensure consistent logging with the existing logging patterns.
=> fix: align log entries to the rest

lib/hybrid-sdk/client/index.ts
Fixes the git commit rule signing loading error.
=> fix: git commit signing rule loading

.circleci/config.yml
Makes main image release behind an approval step for finer release control, without impacting broker package release, adding docker image build and release on preview prefixed tags.
=> chore: add preview image building and prod img behind approval

lib/hybrid-sdk/client/brokerClientPlugins/abstractBrokerPlugin.ts, lib/hybrid-sdk/client/brokerClientPlugins/plugins/containerRegistryCredentialsFormatting.ts, test/unit/plugins/brokerPlugins/containerRegistryCredentialsFormatting.test.ts
Enables context support for the container registry credentials formatting plugin, to extend context support to container integrations using the container registry agent.
Pay special attention to the context memory object accessed via reference despite the shallow copy passed to the startupContext method.
=> feat: add context support to cra plugin [HYB-986]

.snyk, defaultFilters/apprisk/azure-repos.json
- adds https://learn.microsoft.com/en-us/rest/api/azure/devops/core/projects/get-project-properties?view=azure-devops-rest-7.0&tabs=HTTP to allow list
- based on thread : https://snyk.slack.com/archives/C07V07W3C12/p1745481508170309?thread_ts=1743430297.245869&cid=C07V07W3C12
=> feat: add Get Project Properties for apprisk/azure-repos

.github/CODEOWNERS
=> chore: update codeowners file -- move to Access

config.default.json, lib/hybrid-sdk/client/routesHandler/websocketConnectionMiddlewares.ts, test/unit/client/routesHandler/websocketConnectionMiddlewares.test.ts
Adds a list of integrations that are compatible with the CRA.
=> fix: Adds the CRA_COMPATIBLE_TYPES list to default config [HYB-1007]

lib/hybrid-sdk/client/brokerClientPlugins/abstractBrokerPlugin.ts, lib/hybrid-sdk/client/brokerClientPlugins/pluginManager.ts, lib/hybrid-sdk/client/brokerClientPlugins/plugins/containerRegistryCredentialsFormatting.ts, lib/hybrid-sdk/client/brokerClientPlugins/plugins/githubServerAppAuth.ts, lib/hybrid-sdk/client/connectionsManager/synchronizer.ts, lib/hybrid-sdk/common/config/pluginsConfig.ts, lib/logs/logger.ts, test/fixtures/plugins/dummy 3 plugin.js, test/fixtures/plugins/dummy 3 second plugin.js, test/fixtures/plugins/dummy-context.js, test/fixtures/plugins/dummy-multi.js, test/fixtures/plugins/dummy.js, test/fixtures/plugins/dummy2.js, test/unit/plugins/brokerPlugins/containerRegistryCredentialsFormatting.test.ts, test/unit/plugins/brokerPlugins/github-server-app.test.ts, test/unit/plugins/pluginManager.test.ts
This PR fixes the issue that plugins settings were not applied after clientConfig sync.
Partial cherry-pick up from #975 (in draft mode), to make merge of context-related thing easier.
=> fix: ensure that plugin settings applied after clientConfig sync

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/github-server-app/accept.json.sample, defaultFilters/github-cloud-app.json, defaultFilters/github-enterprise.json, defaultFilters/github-server-app.json, defaultFilters/github.json, package-lock.json, package.json
Updates the allowlist to include a couple of new endpoints that are used in GitHub for the new AI Fix feature.
I've also included an update to the `openpgp` package as there was a new high vuln which was failing the pipeline, hope that's ok. I can commit that as a separate PR if needed.
=> feat: allowlist updates for ai fix commit endpoints

defaultFilters/apprisk/azure-repos.json
=> chore(azure-devops): remove redundant rule

lib/hybrid-sdk/client/utils/connectionValidation.ts, lib/hybrid-sdk/client/utils/credentials.ts, test/unit/client/utils/credentials.test.ts
This PR extends and aligns systemcheck for Bitbucket PAT when using Universal Broker (the classic works).
=> fix: align systemcheck for bitbucket by universal broker [ACC-2780]

client-templates/azure-repos/accept.json.sample, defaultFilters/azure-repos.json, test/unit/filters-and-interpolates.test.ts
- Adds rule for Azure Repos to allow posting pull request thread comments.
- Updates test fixtures.
=> feat: azurerepos post comment thread rule [TREX-2310]
