snyk/broker

lib/healthcheck.js, lib/webserver.js, test/functional/healthcheck.test.js
Add's a simple health check to the client and server at `/healthcheck`
Fire up a broker server and client, and curl `/healthcheck` on each.
This is useful when running the broker server behind a load balancer. It has been also included on the client in case it proves useful in future (and to keep the codebase simple).
=> chore: add healthcheck for both client and server

lib/server/index.js, lib/server/socket.js, test/functional/client-pool.test.js
Fixes an issue when 2 clients using same `BROKER_TOKEN` can unintentionally disconnect each other. 
Run a server, connect 2 clients and then disconnect the one that connected first.
Happened when Heroku was rotating the dyno:
- 1st client was connected and running
- Heroku started 2nd Client dyno, it connected to the broker server and correctly became the primary client for specified token
- 1st dyno was shut down, but it sent a `close` event, removing 2nd dyno as well
The result was that both Server and Client was running and Client had no idea it was disconnected.
It also opens up a possibility to run a fleet of clients as failovers
=> test: multiple clients connecting

lib/server/socket.js
The online/offline events only work on the Primus client so this patch removes the listeners for these events from the server.
See https://github.com/primus/primus/blob/b1c33dfc1439ad6df8add9435246bcf1130532d2/primus.js#L248-L260 and https://github.com/primus/primus/blob/b1c33dfc1439ad6df8add9435246bcf1130532d2/primus.js#L555-L603.
=> chore: remove listeners for online/offline events on primus server

client-templates/snyk/accept.json.sample
Updates the Snyk client-template to accept requests relating to Rubygems repositories.
=> feat: add Ruby support to Snyk client template

lib/client/index.js, lib/healthcheck.js, lib/index.js, lib/server/index.js, lib/server/socket.js, lib/webserver.js, test/functional/healthcheck.test.js
adds the client's connection status to the server healthcheck.
run both a server and a client locally. call `/healthcheck` before and after stopping the client, and then restart the client again and call `/healthcheck` again.
=> feat: add clients' health endpoint

lib/client/socket.js, lib/filters/index.js, lib/index.js, lib/log.js, lib/relay.js, lib/server/index.js
Sanitises broker and github tokens from logs.
Uses [bunyan serializers](https://github.com/trentm/node-bunyan#serializers) to do the trick. Requires sensitive tokens to appear in properly named keys of logged objects.
=> fix: sanitise sensitive tokens from logs

client-templates/snyk/accept.json.sample, lib/filters/index.js, test/fixtures/client/filters.json, test/functional/server-client.test.js, test/utils.js
Escapes urls before they are tested against filters.
For example, a request might be something like
`GET https://raw.githubusercontent.com/USER/REPO/COMMIT-ISH/path%2Fto%2Fpackage.json`, but should be unescaped before tested against a rule like
```
{
"//": "used to determine the full dependency tree",
"method": "GET",
"path": "/:name/:repo/:branch*/package.json",
"origin": "https://${GITHUB_TOKEN}@${GITHUB_RAW}"
}
```
(the `%2F`s are replaced by a `/`s to create `https://raw.githubusercontent.com/USER/REPO/COMMIT-ISH/path/to/package.json`)
=> fix: unescapre urls when testing filters, to support custom file locations

lib/webserver.js, test/utils.js
Env vars are expanded and camelified for the broker, so `process.env.HTTPS_KEY` becomes `httpsKey`. Renamed server options to match this convention, as documented in README.md
Based on a patch provided by @radekk
=> fix: https support relies on proper env vars

lib/server/socket.js, test/functional/client-server.test.js
BREAKING CHANGE: standardising BROKER_TOKEN to lowercase
Without this change, an uppercase token on the client may not work against an expected lowercase token on the server side, creating a mismatch.
=> feat: lowercase BROKER_TOKEN when identifying with server

package.json
engine.io-client 3.1.1 has been released without the pinned vulnerable dep, switching back.
=> fix: switch back to released engine-io.client

cli/init.js, lib/relay.js, package.json, test/fixtures/client/filters-https.json, test/fixtures/client/filters.json, test/fixtures/server/filters.json, test/functional/client-server.test.js, test/functional/server-client.test.js, test/utils.js
In a case when a request url contains HTTP credentials
on the url, we want to prefer them over the auth header.
The resolution is to strip the Authorization header.
From:
`Authorization: auth https://user:name@someapi.com/v1/repos`
To:
`https://user:name@someapi.com/v1/repos`
=> fix: prefer supplied url creds over auth header

lib/server/index.js, test/functional/healthcheck.test.js
Move the check of client connection-status from `GET /broker/:broker-token` to
`GET /connection-statis/:broker-token`, to avoid interfering with actual
brokered requests.
=> fix: dedicated connection-status endpoint

client-templates/github/accept.json.sample
Updates the Snyk client template to add two new whitelist rules needed for opening Snyk Fix Pull-Requests against GitHub Enterprise instances.
=> fix: update Snyk template to support Snyk Fix PRs on GitHub Enterprise

client-templates/bitbucket-server/accept.json.sample, client-templates/github/accept.json.sample
We want to be able to fetch `requirements.txt` files to detect Python projects. This change adds a default filter to allow fetching these files both from GitHub and Bitbucket.
In order to make use of this change, either generate a new `accept.json` filter by running `broker init [github|bitbucket]`, or apply this patch to your existing `accept.json` file.
=> feat: allow fetching requirements.txt to support Python projects

client-templates/github/accept.json.sample
Adds `pom.xml` to the list of allowed files on commit webhooks. This will allow Snyk to update project state when the relevant `pom.xml` file changes in the repo.
=> feat: include pom.xml in allowed webhook data to monitor changes in Maven projects

client-templates/bitbucket-server/accept.json.sample, client-templates/github/accept.json.sample
Adds `yarn.lock` as an allowed file for filtering in GitHub commit webhooks and GET requests from repos.
=> feat: allow filtering for yarn.lock files to support Yarn projects

dockerfiles/bitbucket-server/Dockerfile
Exposes `PORT` in the Bitbucket Server Dockerfile. Although webhooks are not yet supported when brokering Bitbucket Server, this change allows customisation of the broker client's port when running the client container.
=> fix: expose PORT in bitbucket-server Dockerfile

dockerfiles/bitbucket-server/Dockerfile, dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile
Docker images' base changes from `node:6-alpine` to `node:6-slim`. The image will be bigger in size.
I am seeing sporadic segfaults of the broker client image in our env, trying to rule out one potential root cause.
=> feat: rooting out sporadic segfaults in docker images

dockerfiles/bitbucket-server/Dockerfile, dockerfiles/github-enterprise/Dockerfile
Rearranges grouping of env vars in Dockerfiles so that all custom vars and their derivatives are in the custom vars group.
=> fix: env vars that depend on custom ones are also custom

dockerfiles/bitbucket-server/Dockerfile, dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile
Now that `/healthcheck` is configurable via an env var, all dockerfiles follow suit and allow customisation of the healthcheck path.
=> fix: use env healthcheck path in dockerfiles

client-templates/bitbucket-server/accept.json.sample, client-templates/github/accept.json.sample
Adds `build.gradle` and `build.sbt` to the default `accept.json` filters of the GitHub and Bitbucket Server client configs.
=> feat: whitelist gradle and sbt manifest files by default

client-templates/gitlab/accept.json.sample
Adds `GET /api/v4/user` to default Gitlab accept filter to support token validation for Snyk access.
=> fix: allow token validation on gitlab default rules

lib/filters/index.js, lib/relay.js
Allows filtering requests by HTTP headers.
Specifically, supports Gitlab `private-token` header replacement.
=> fix: allow filtering by request headers

package.json
Removes `snyk` dependency and the `snyk-protect` npm target.
These were introduced by a fix PR that ignored an issue, and are meant to facilitate patching. No patching is required right now, removing this until required by a patched vuln.
=> fix: remove snyk-protect target as no patching is required

client-templates/gitlab/accept.json.sample
Adds support for GitLab webhooks:
- hook creation
- hook deletion
- commit status creation
- fowards webhooks onwards
=> feat: add support for gitlab webhooks

client-templates/bitbucket-server/accept.json.sample, lib/relay.js
Rules for supporting bitbucket-server webhooks through the broker. The intended behavior will be to create and delete webhooks, and to send commit messages (from Snyk to Bitbucket-Server); and to receive webhook events (from Bitbucket-Server, and into Snyk).
=> feat: rules for bitbucket-server webhooks (ingress and egress)

lib/filters/index.js, test/functional/server-client.test.js
fix: when sending a query param that has a "?" inside (i.e. a callbac…d internal query params were broken due to querystring split.
This pr adds a test and fixes the issue.
=> fix: url in query parameter breaks querystring relaying

lib/log.js, package.json
This change makes sure that tokens which have special meaning in regular expressions don't break the log sanitisation.
=> fix: ensure tokens are sanitised from logs

lib/webserver.js
The default size limit for `body-parser` is 100kb (see https://www.npmjs.com/package/body-parser#limit-1). This causes the broker to reject requests with larger body sizes. 413 is returned on the response by the `body-parser` middleware with direct output to the console in the following form:
```
Error: request entity too large
at readStream (/usr/local/lib/node_modules/snyk-broker/node_modules/raw-body/index.js:196:17)
at getRawBody (/usr/local/lib/node_modules/snyk-broker/node_modules/raw-body/index.js:106:12)
at read (/usr/local/lib/node_modules/snyk-broker/node_modules/body-parser/lib/read.js:76:3)
at rawParser (/usr/local/lib/node_modules/snyk-broker/node_modules/body-parser/lib/types/raw.js:81:5)
at Layer.handle [as handle_request] …
```
=> fix: allow requests with over 100kb in body length

README.md, client-templates/github/.env.sample, client-templates/github/accept.json.sample, dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile, lib/relay.js, test/fixtures/client/filters.json, test/functional/server-client.test.js, test/utils.js
Since GH enterprise 2.11 the `/raw` endpoint is not supported.
In order for us to make a gradual change without breaking our users broker clients
I added logic that rewrites /raw to /repos/owner/repo/contents endpoint.
Once all of our GHE users will use the we could change all our system code that touches GH files, or hopefully will do it on the GH agent, and delete this code.
I know that this code makes our filter logic GH aware, and this was not the intention of the broker, but this was the solution for non breaking change.
https://snyksec.atlassian.net/browse/CSUP-4
=> feat: rewrite raw endpoints to /contents api for GH

client-templates/gitlab/accept.json.sample
Supports the APIs needed for opening fix merge request on gitlab.
=> feat: allow APIs used for creating fix merge request

client-templates/bitbucket-server/accept.json.sample
Adds APIs used for creating fix pull request on bitbucket-server in the template `accept.json`
`client-templates/bitbucket-server/accept.json.sample`
=> feat: allow APIs used for creating fix pull request on bitbucket-server

client-templates/gitlab/accept.json.sample
adds the path `/api/v3/projects/visible` to the GitLab client template.
=> feat: allow a GET to api/v3/projects/visible on GitLab

.gitignore, client-templates/github/.env.sample, client-templates/github/accept.json.sample, lib/filters/index.js, test/fixtures/relay.json, test/unit/filters.test.js
adds the ability to query github's graphql through the broker, by adding a new set of filters/rules: body regex.
One new such regex is added to the github broker sample to allow this specific graphql query, but no others.
=> feat: allow graphql queries to pass through the broker

dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile
The default .env template for github set the GraphQL endpoint to $GTIHUB/api, which is correct for GHE, but incorrect for github.com.
Overriding the default .env template values in the Dockerfile for both github.com and GHE to fix github.com endpoint, and be explicit about this setting
=> fix: github graphql endpoint for github-com docker image

lib/server/index.js, test/functional/healthcheck.test.js
When checking for the status of a specific connection, expose the versions of all clients and not just the first one. This is done to improve visibility into number of client connections for the same token, and their versions.
=> fix: expose metadata of all clients on connection-status

client-templates/bitbucket-server/accept.json.sample
Adds a rule in the bitbucket server template to allow checking for a repo's default branch.
=> fix: allow default branch checking on bitbucket server template rules

.travis.yml
Remove dockerhub build trigger from travis settings, as dockerhub is monitoring the repo directly and builds on new tags.
=> chore: docker build trigger is within dockerhub

client-templates/github/accept.json.sample
Adds access to branch status checks on GitHub. This will allow Snyk to convert from one version of Snyk status checks to another, needed for smooth migration purposes only.
=> feat: allow access to branch status checks on github

client-templates/bitbucket-server/accept.json.sample
Modifies `accept.json` template for bitbucket-server broker clients to allow fix PRs for nested manifest files.
=> fix: fix PRs for nested files in bitbucket-server

lib/try-json-parse.js, test/unit/try-json-parse.test.js
when getting the body it could be a string representation of null, meaning 'null'...
in this case Buffer.from('null') will return 'null' and JSON.parse will parse it as null.
eventually this chain of event will cause tryJsonParse to return null and relay.js will fail on line 114
because parsedBody will be null.
=> fix: consider the case where body is 'null'

dockerfiles/github-com/Dockerfile
=> chore: fix typo in github Dockerfile comment (hos -> host)

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample, lib/filters/index.js
- Allow a new manifest type `packages.config` for .NET projects
This is part of the planned work around .net & .net core SCM support
=> feat: Include packages.config in a list of allowed manifest files

README.md, client-templates/bitbucket-server/.env.sample, client-templates/github-com/.env.sample, client-templates/github-enterprise/.env.sample, client-templates/gitlab/.env.sample, client-templates/jira/.env.sample, dockerfiles/bitbucket-server/Dockerfile, dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile, dockerfiles/gitlab/Dockerfile, dockerfiles/jira/Dockerfile, lib/client/index.js, lib/index.js, lib/log.js, lib/relay.js, test/functional/healthcheck.test.js, test/functional/systemcheck.test.js
Adds a `/systemcheck` endpoint to the broker client, which pokes a configured validation URL, asserting network reachability and some credentials correctness of the broker client configuration. Main purpose is to assist in troubleshooting of connectivity / application issues.
Environment variables configuring the systemcheck:
`BROKER_CLIENT_VALIDATION_URL` - the URL to test
`BROKER_CLIENT_VALIDATION_METHOD` - the HTTP method, default `GET`
`BROKER_CLIENT_VALIDATION_TIMEOUT_MS` - the HTTP request timeout, default 5000ms
`BROKER_CLIENT_VALIDATION_AUTHORIZATION_HEADER` - the `Authorization` header value to be used on the request, default none
`BROKER_CLIENT_VALIDATION_BASIC_AUTH` - the basic auth creds to be base64-encoded and used for the `Authorization` header value, default none
=> feat: broker client systemcheck endpoint

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
Update the relevant client templates to support fetching a single repo
https://snyksec.atlassian.net/browse/SC-6291
Needed to support the import API. Some useful links I used to determine the endpoints needed:
https://github.com/snyk/bitbucket-server-agent/commit/de6f8410ed7e0c7b55d97e599fa147960858b2bb
https://github.com/snyk/gitlab-agent/blob/develop/lib/gitlab/client.js
https://github.com/snyk/github-agent/commit/a9c5f63e37a2b6d2af3c73718f8aac179cfbb6af
https://developer.github.com/v3/repos/#get
=> feat: add support for getting a single repo

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
- Allow a new manifest type `*.vbproj` for .NET projects
This is part of the planned work around .net & .net core SCM support
=> feat: allow vbproj files

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
Adds support for .fsproj files through the broker
1. Create a local broker client
2. Import repo containing .fsproj file from different SCs
=> feat: allow .fsproj files through the broker

client-templates/bitbucket-server/.env.sample, client-templates/github-com/.env.sample, client-templates/github-enterprise/.env.sample, client-templates/gitlab/.env.sample, client-templates/jira/.env.sample, dockerfiles/bitbucket-server/Dockerfile, dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile, dockerfiles/gitlab/Dockerfile, dockerfiles/jira/Dockerfile
This fixes a problem where the broker is working correctly but system check does not work because the url in the env vars isn't defined.
=> fix: make sure that env vars always exist

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
This PR adds support for project.json dotnet dependencies.
Fire up a local Broker for any of the SCMs and add a repo containing a project.json file. Do a search for snyk-fixtures/dotnet-project-json, there is a repo for GitHub, GitHub Enterprise, Bitbucket Server and GitLab for testing.
I've tested this for each SCM but to test manually yourself try adding a repo containing a project.json using a Broker for each SCM.
=> feat: Adds support for project.json dependency files.

client-templates/gitlab/accept.json.sample
In order to support search on PAS on Gitlab, new endpoints were added.
=> feat: gitlab adding new endpoints for searching projects

client-templates/gitlab/accept.json.sample
admin user couldn't see other user's project. that resulted on us showing only partial data on PAS page. and crashed whenever searching something that is owned by other user.
adding users endpoint.
=> fix: gl missing projects when using admin user

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample, package-lock.json
feat: enable fetching manifests for Go vendor and dep package managers.
https://snyksec.atlassian.net/browse/BST-572
https://snyksec.atlassian.net/browse/BST-573
**Note:** All the file names seem to be path-independent, so I should not write `vendor/vendor.json`, right?
=> feat: enable fetching manifests for Go vendor and dep package managers.

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample, lib/filters/index.js, test/fixtures/client/filters.json, test/functional/server-client.test.js, test/utils.js
(https://github.com/snyk/broker/blob/master/.github/CONTRIBUTING.md) rules
We used to decode urls to 'help' them match the approve filters. This is misguided as the broker is not supposed to 'mangle' the requests it is proxying on top of what is defined in the approve filters.
This is breaking some functionality when the proxied service expects an encoded URL, but the broker decodes it.
Applying this change will require adjustment of our pre-defined approve filters. For example, approving the fetching of `package.json` files in any depth of a git repo will require approving `.../package.json`, `...%2Fpackage.json`, `...%252Fpackage.json` and so on. The needed changes to the pre-defined approve filters will follow on a separate commit.
=> fix: do not decode urls when proxying them

client-templates/github-enterprise/accept.json.sample
We allow `vendor.json` to be anywhere, not only on `vendor` folder and this behaviour breaks import for GHE brokered customers.
=> fix: align vendor.json handling

client-templates/bitbucket-server/accept.json.sample
Continuing work begun in https://github.com/snyk/broker/pull/171, this PR allows `vendor.json` to be anywhere in the repo, not specifically in `vendor` folder.
=> fix: align vendor.json for bitbucket as well

client-templates/bitbucket-server/accept.json.sample
Adds a `/files` endpoint, used by recursive manifest search, to the sample Bitbucket Server accept.json
https://snyksec.atlassian.net/browse/COMET-241
=> Add /files endpoint to BBS accept.json sample

lib/relay.js
Reduce the log level of the `sending response back to websocket connection` message to debug in case the response is 2XX
=> fix: make response log less noisy

lib/client/index.js
Context on systemcheck: https://github.com/snyk/broker/pull/137
Currently, when systemcheck fails with a 401 (Unauthorized) the error returned is not very helpful.
This PR adds a helpful error message.
=> feat: improve systemcheck 401 error messages

client-templates/gitlab/accept.json.sample
Adds allow rule for full depth manifest discovery  API for Gitlab
=> feat: support full depth manifest discovery for Gitlab

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample
Updates the contributors API for GH and GHE to use /commits instead of /contributors endpoint. This allows counting devs in a specific time range.
=> feat: update GH and GHE contributors API

lib/relay.js, test/functional/client-server.test.js, test/functional/server-client.test.js
1. Improves an error message when request is blocked because of the policy
2. Changes the body of the error message from plain text to json format of {message, reason}, where `message` will be the error message sent before and `reason` will be a block reason (when there's no a matching accept rule in accept.json file)
=> fix: improve broker error messages

client-templates/gitlab/accept.json.sample
Updates Gitlab's contributors endpoint to /commits (instead of /contributors). This aligns Gitlab with the other SCMs and allows counting the last 90 days contributors.
=> feat: gitlab new contributors API

client-templates/gitlab/accept.json.sample
Add commit [endpoint](https://docs.gitlab.com/ee/api/commits.html#get-a-single-commit) to GitLab's whitelist. 
This needs for caching functionality, to avoid unnecessary requests to SCM and increasing dependencies test speed.
=> feat: add GitLab commit endpoint to whitelist

client-templates/bitbucket-server/accept.json.sample
Adding new proxy for fetching single commit via [Bitbucket Server API](https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#idm8283038112). The purpose is faster dependency discover process and caching in broker usage cases.
=> feat: added mapping for getting single commit endpoint

README.npm.md, lib/client/socket.js, lib/filters/index.js, lib/relay.js, lib/server/socket.js, package-lock.json, package.json, test/fixtures/client/filters.json, test/fixtures/server/filters.json, test/functional/server-client.test.js, test/utils.js
Adds support for streaming of binary data. Using the `data` and `end` events the request response on the client side is switched to streaming and each received `chunk` is send over the websocket. The server forwards each received `chunk` directly to the consuming service.
=> feat: Support for binary data streaming

lib/client/socket.js
This PR adds the Broker ID to the initial connection URL when a client connects to the server. This change is required for load-balancing requests to the server.
=> feat: Use Broker ID during initial client registration

lib/relay.js, lib/server/index.js, test/functional/healthcheck.test.js, test/functional/server-client.test.js
The connection-status endpoint will now return a list of filters. 
This will help debugging Broker issues caused by the filters (usually outdated filters).
=> feat: connection status return filters

lib/relay.js, test/functional/client-server.test.js, test/functional/server-client.test.js
Adds the target url (this is actually a path, doesn't contain the origin) to the Broker errors so that we can understand why was a request blocked.
=> feat: add url to blocked error

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
Allow us to grab the gradle.properties file to help with gradle
project dependency generation.
We are starting to roll out this file to be picked up on every test run if present. It is currently rolled out to 10%
Adding broker support as well
=> feat: allow gradle.properties file

lib/client/index.js, test/functional/client-ca.test.js, test/utils.js
`CA_CERT` envvar was ignored for `/systemcheck` endpoint, which resulted in false negatives when checking whether self-signed certificates are setup correctly
=> Use CA_CERT for /systemcheck endpoint

lib/log.js, test/unit/log.test.js
We have found out that some tokens can be unintentionally logged by broker client through recently added httpUrl and ioUrl log keys. This regression was introduced in 5a8213afc.
Fix this, and also add a test for keys sanitization.
=> fix: log sanitization of sensitive info

.travis.yml
* Updates CI to use node10 to catch up with a change in `semantic-release` that wasn't backwards-compatible with node8
=> chore: sem-rel needs node 10 now

client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
Allow broker to pass through the 'Packages.props', 'Directory.Build.props', 'Directory.Build.targets' these are .Net files where users can pin dependencies
=> feat: allow nuget props and target files

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample
Added missed url masks for [getting PR data](https://developer.github.com/v3/pulls/#get-a-single-pull-request) from GitHub and GitHub Enterprise API.
This data needs fo covering all changes in vuln testing, that were introduced in PR (open/reopen PR to default branch).
=> feat: add missed url masks for supporting merge SHA functionality

client-templates/artifactory-cr/accept.json.sample
Please credit THG if change is accepted.
- [ Y ] Ready for review
- [ Y ] Follows [CONTRIBUTING](https://github.com/snyk/broker/blob/master/.github/CONTRIBUTING.md) rules
Fix for Artifactory CR integration. Snyk is not calling the v2/token endpoint and using the Token for auth. As a result, you need to add the auth basic scheme to every v2/* call otherwise you will get 401 unauthorised.
Tested that adding this resolves the issue with authentication.
Review if v2/token is called by snyk server and whether or not it is used in subsequent calls to confirm hypothesis.
Need a local testing artifactory CR instance
Have tried this in production and proven that 401 Unauthorised errors is due to lack of auth on the calls. Alternatively can also use a JFROG API key instead.
First PR we submitted …
=> fix: Resolve 401 error with Artificatory CR Integration

.gitignore, lib/filters/index.js, test/fixtures/accept/github.json, test/fixtures/relay.json, test/unit/filters.test.js
Currently information after a fragment identifier in the url provided to the broker client is not sanitised and could theoretically be exploited (only by a malicious Snyk Broker Server) with a path that matches a filter because it has a manifest file after the fragment.
This sanitises the URL by removing any information found after a fragment identifier (`#`) in the provided path.
See the new tests in `test/unit/filters.test.js`
A request to broker client providing the following path should fail:
`/repos/owner/repo/contents/sensitive-file.js#/package.json`
=> fix: discard any information in url after a fragment identifier

lib/filters/index.js, test/fixtures/accept/github.json, test/unit/filters.test.js
The GitHub API will follow dot-dot-slash (`../`) sequences and there is currently no sanitisation of this in the broker.
Whilst none of the existing examples suggest to do this, if a client was to whitelist a folder (e.g. `/path/to/docs/*`) then path traversal could be used to access a sensitive file e.g.
`/path/to/docs/../../path/to/sensitive/file.js`.
This changes that so that if a [normalized path](https://nodejs.org/api/path.html#path_path_normalize_path) does not match the original path then the request is rejected.
=> feat: reject paths with path traversal

lib/log.js, test/unit/log.test.js
Adds sanitise call onto all origin entries as origin can expose highly sensitive credentials. For Github, the origin URL includes the highly sensitive GITHUB_TOKEN which enables branch, commit, merge, repo access.
Duplicate of #231 but with the log tests updated. 
Github broker integration, turn logging onto debug.
=> fix: sanitize origin in logs

lib/relay.js, package.json, test/functional/server-client.test.js, test/utils.js
Remove Accept-Encoding header to not corrupt gzip encoded requests
While working with @darscan on this we found out that broker was never passing back into the client compressed content. So broker-client was always decompressing it and sending back the decoded content, but leaving in headers 'Content-Encoding': 'gzip,deflate'. This was making npm cli to freak out as it couldn't decode already decoded content.
This PR removes 'Accept-Encoding' header which means that content will always be plain for now
Renaming and adding test from that PR
https://github.com/snyk/broker/pull/221
=> feat: remove Accept-Encoding header to not corrupt gzip encoded requests

README.md, lib/relay.js
To improve auditability of the Broker client, this raises the log level of HTTP200 responses to INFO so they are included in the logs by default.
It also adds a new config parameter which allows the SCM response body to be logged by the client if required.
=> feat: improve auditability of broker

lib/client/socket.js
Due to the latest outage, there was an issue with Broker clients reconnecting back to the Broker server. During investigation was uncovered that Broker client will try to reconnect for around 16-18 minutes (re-connect time is randomized).
To improve the user experience during outages, the time of waiting is increased by changing the number of retries and decreasing exponential growth factor.
Previously, we were using the default Primius strategy: 10 retries with exponential growth factor 2.
In this PR, retries are increased to 20 and factor is decreased to 1.5. Which gives us a window between one and one and a half hours to reconnect.
Added logging for each attempt and proximate time till retry.
Added graceful process shutdown to add visibility on the customer side to restart Broker …
=> feat: increase reconnect waiting time

README.md, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, lib/filters/index.js, test/fixtures/accept/github.json, test/fixtures/client/filters-https.json, test/fixtures/client/filters.json, test/fixtures/relay.json, test/fixtures/server/filters.json, test/functional/client-server.test.js, test/unit/filters.test.js, test/utils.js
Adds the ability to filter by request headers using `accept.json`. The filtering is strict so, rather than just matching values, if a header is defined in the whitelist and the request does not include the expected header key it will fail.
Make a brokered request to the GitHub Commits API using the `application/vnd.github.cryptographer-preview` header and it will get blocked.
=> feat: add request header filtering

client-templates/gitlab/accept.json.sample
Removes the whitelist entries for the Repository Commits API in GitLab now that usage has been replaced with Repository Files calls.
=> feat: remove repository commits API from GitLab whitelist

lib/config/index.js, package.json
Upgrading these two deps, which require minimal changes, removes our transitive dependency on `lodash`, and the need for patches.
`snyk-config` upgrade changes it to an exported function, which we can call.
`node-cache` upgrade:
1) removes deprecated api, which we aren't using
2) drops support for node <8, which we don't support
=> feat: bump deps (no more lodash)

client-templates/artifactory/.env.sample
Artifactory broker uri was aimed at the container broker (which doesn't exist anymore); Was swapped for the standard `broker.snyk.io`
=> fix: allowing brokered artifactory to communicate w/ Snyk

dockerfiles/artifactory/Dockerfile, dockerfiles/bitbucket-server/Dockerfile, dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile, dockerfiles/gitlab/Dockerfile, dockerfiles/jira/Dockerfile
`ca-certificates` was removed from the underlying images when moving to `node:12-buster-slim`, this adds the package to make commands like `update-ca-certificates` available again.
=> feat: add ca-certificates to all broker images

.npmignore, cli/index.js, lib/version.js, package.json, tsconfig.json
Enable tsc's `resolveJsonModule` flag to copy the package.json to dist, so we can require the package.json at the same file path as we did before using TS. This is needed because the npm package env vars are only populated when the application is run by npm, which isn't how we start broker. Also moved from using the package.json "files" field to `.npmignore`, as the nested package.json in dist/ did not play nicely when packaging
=> fix: Correctly load version from package.json

cli/index.js, cli/init.js, test/functional/init.test.js
The args for the CLI interface were being passed through incorrectly, causing broker setup to fail. This patch should align them as expected.
=> fix: CLI interface args were passed incorrectly

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, test/fixtures/client/github/graphql/find-pull-requests-closed.txt, test/fixtures/client/github/graphql/find-pull-requests-open.txt, test/fixtures/relay.json
This change enables the broker to call the graphql pull request node with rateLimit parameter. Previously not having
this in the regexp would block outgoing requests with rateLimit present.
Taking a look at whether the right files were changed. The broker should be able to call graphql endpoint without being blocked.
-
-
-
-
=> fix: added rateLimit to allowed github graphql query params

dockerfiles/azure-repos/Dockerfile
Remove `BROKER_CLIENT_VALIDATION_BASIC_AUTH` env variable in Dockerfile. That's done to prevent run misconfigured docker image
=> fix: remove env variable from azure-repos Dockerfile

client-templates/azure-repos/accept.json.sample
Small fix of Azure broker client whitelist. Matching rules do not accept boolean values
=> fix: replace boolean values by strings in whitelist rules

test/fixtures/accept/github-big-files.json, test/unit/filters.test.ts
Adds a test for a rule that allows getting file shas via the github graphql API - the file sha is used as a parameter for the blobs (big files) API.
The rule is not part of the default accept.json but useful for some Broker users that need to support big files.
=> test: github big file rule

client-templates/github-enterprise/accept.json.sample
The GITHUB_RAW endpoint is only used for Github (not enterprise) and was unused in this config. Guess it got here accidentally by replicating github.com rules into the enterprise accept.json.
- Snyk never calls this endpoint for a GHE integration
- the .env.sample doesn't mention this property so probably it's not set in any GHE Broker client
- the raw endpoint Snyk uses is always `raw.githubusercontent.com` so no way that would work with GHE
=> chore: remove unused ghe broker rules

test/fixtures/accept/ghe.json, test/unit/filters.test.ts
A [customer ticket](https://snyk.zendesk.com/agent/tickets/7256) has lead to this potential solution where the current GHE `accept.json` template has suggested an invalid uri for scanning a Dockerfile with an encoded path.
This PR removes the extra irrelevant `2F` from the rule's uri path.
=> fix: make encoded ghe accept json /dockerfile path valid

dockerfiles/artifactory/Dockerfile
Update artifactory base image to use less vulnerable node:12-buster-slim image instead node:12-slim.
And add an env variable necessary for NPM.
=> fix: update artifactory dockerfile to use less vulnerable node:12-buster-slim

dockerfiles/azure-repos/Dockerfile
Use less vulnerable base `node:12-buster-slim` image instead `node:12-slim`
=> feat: use less vulnerable node:12-buster-slim

client-templates/azure-repos/accept.json.sample
This patch updates the Azure Repos sample accept.json to include a new rule that allows post PR statuses. Until now, Snyk only supported commit statuses, which are different from PR statuses for Azure Repos
See https://github.com/snyk/azure-repos-agent/pull/219 for the implementation of this endpoint in the Azure Repos agent
=> feat: Support PR statuses for brokered Azure Repos

README.md, client-templates/container-registry-agent/.env.sample, client-templates/container-registry-agent/accept.json.sample, dockerfiles/container-registry-agent/Dockerfile
Add broker support for container-registry-agent by providing:
* template: accept.json, env
* Dockerfile to build image
* README section
=> feat: Add container registry agent support

lib/relay.js
This patch introduces wrapping sending websocket response back with `try..catch`.
This will help us mitigate the problem with unexpected error:
`TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of
type string or an instance of Buffer or Uint8Array. Received an instance of Object`
=> fix: wrap websocket response handler to prevent broker crashing

lib/log.js, test/unit/log.test.ts
This patch needs to prevent logging of artifactory url, which might contain basic auth credentials.
=> fix: add sanitization logic for artifactory url

client-templates/artifactory/.env.sample, lib/client/index.js
This patch fixing 406 error of `/api/system/ping` endpoint. It returns `text/plain` response
and not allow to pass `application/json` header.
=> fix: artifactory systmecheck endpoint

client-templates/container-registry-agent/accept.json.sample
Adjust the list tags path to allow repo paths that contain slashes. This is required to support Harbor CR in a brokered environment.
=> fix: container registry agent list tags path

lib/log.js, test/unit/log.test.ts
Added sanitization for brokered container registry environment data
=> fix: sanitize CR env data in logs

client-templates/azure-repos/accept.json.sample
Fixes the rule which allows for Fix PRs to be updated in Azure Repos.
It was missing a bit to allow for the PR ID.
The URLs for this API look like: `<base-url...>/<project-name>/_apis/git/repositories/<repo>/pullrequests/<pr-id>`
So we need to account for the `/<pr-id>` part.
=> Add :pullRef (PR ID) to path for updating fix pr

dockerfiles/artifactory/Dockerfile, dockerfiles/azure-repos/Dockerfile, dockerfiles/bitbucket-server/Dockerfile, dockerfiles/container-registry-agent/Dockerfile, dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile, dockerfiles/gitlab/Dockerfile, dockerfiles/jira/Dockerfile, dockerfiles/ubuntu/Dockerfile
Updates all dockerfiles to use base image with a reduced vuln count.
The update includes a new much remediated image (built on top of an ubuntu image) vs. the original image in use. We assessed the vulns in both images and determined they can not be exploited when used to run the broker.
=> feat: update all agent dockerfiles with new remediated image

client-templates/azure-repos/accept.json.sample, client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
Add `gradle.lockfile` sample in all SCM integrations' client-templates `accept.json.sample`
files, in order to enable customers using broker of successfully scan
their gradle projects containing lockfiles.
=> feat: add gradle lockfile in client templates

client-templates/azure-repos/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/accept.json.sample
* Add `Dockerfile` update sample in all SCM integration' client-templates `accept.json.sample` files, in order to enable customers using broker to successfully update their Dockerfiles using Dockerfile Fix PR.
* Add `Dockerfile` get sample in GitHub Enterprise client-templates `accept.json.sample` file, in order to enable customers using broker to successfully scan their Dockerfiles.
* Azure Repos
* Bitbucket Server
* GitHub Com
* GitHub Enterprise
* GitLab
=> feat: add dockerfile update in client templates

lib/replace-vars.js, test/unit/replace-vars.test.ts
Allow usage of internal domain name for snyk-hosted broker server
>This should come AFTER the ops pr https://github.com/snyk/ops/pull/3301 and BEFORE https://github.com/snyk/npm-deps/pull/427
=> feat: internal broker url for rewrites

lib/server/socket.js
The Broker Server has a limit of 10MB per socket payload. When sending a bigger payload, the socket connection is killed.
This PR increases that max payload size from 10MB to 20MB (issue was found with 15MB payloads).
More details about this parameter:
-`maxLength` in https://github.com/primus/primus#getting-started
-`maxHttpBufferSize` in https://github.com/socketio/engine.io#methods-1 - `how many bytes or characters a message can be, before closing the session`
=> feat: support bigger payloads (broker server)

.github/CODEOWNERS, .travis.yml, bin/container-registry-agent/docker-entrypoint.sh, client-templates/container-registry-agent/.env.sample, dockerfiles/container-registry-agent/Dockerfile, package.json, test/bin/container-registry-agent/docker-entrypoint-test.sh, test/bin/shunit2
Simplify credentials set up for container-registry-agent broker client. Allow passing multiple single env vars, instead of setting up massive base64-encoded json encompassing all the data in a single CR_CREDENTIALS env var.
For example, you can pass env vars CR_TYPE, CR_USERNAME, CR_PASSWORD and CR_BASE, and the correct json structure will be set automatically.
This approach is backwards-compatible with clients directly using CR_CREDENTIALS, however it will be deprecated in the future.
Remove default CR_CREDENTIALS from dockerfile and template, in order to allow using simple env vars and avoid confusion arising from different env vars for different container registries.
Also add tests for credentials setup inside CRA docker entrypoint script. It uses shunit2 dependency for basic sh unit …
=> feat: Simplify credentials setup for CRA broker client

bin/container-registry-agent/docker-entrypoint.sh, test/bin/container-registry-agent/docker-entrypoint-test.sh
This is continuation of #328.
It adds support for newly added DigitalOcean CR, which has specific credentials format.
Additionally, order of args in test assertions is fixed in the last commit.
=> Feat: container registry agent support for DigitalOcean CR

.circleci/config.yml
`node_modules` are necessary to compile the typescript for the release build.
https://app.circleci.com/pipelines/github/snyk/broker/16/workflows/2664c3ee-7147-4a33-b044-57e062fb57d8/jobs/48
=> chore: fix release

client-templates/azure-repos/.env.sample, client-templates/azure-repos/accept.json.sample, client-templates/bitbucket-server/.env.sample, client-templates/bitbucket-server/accept.json.sample, client-templates/github-com/.env.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/.env.sample, client-templates/github-enterprise/accept.json.sample, client-templates/gitlab/.env.sample, client-templates/gitlab/accept.json.sample, dockerfiles/azure-repos/Dockerfile, dockerfiles/bitbucket-server/Dockerfile, dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile, dockerfiles/gitlab/Dockerfile, lib/log.js, lib/server/index.js, test/fixtures/client/filters.json, test/functional/server-client.test.js, test/unit/log.test.ts, test/utils.ts
As part of the efforts to allow on-prem customers to have Snyk Code analysis results, we've built a support service that can be run alongside the Broker Client to clone the repositories and upload the code to our servers to be analyzed. In order to support this solution, we've updated the Broker Client to be aware of this new architecture and redirect all the requests to a specific endpoint towards the new snyk git client.
The expected behaviour at the moment is:
- a new `GIT_CLIENT_URL` variable is introduced in the `.env` file to be specified by the customer during the deployment, alongside three support variables `GIT_URL`, `GIT_USERNAME`, `GIT_PASSWORD` that are just used to capture under a common name different SCM-related variables that already present.
- every request towards …
=> feat: add redirect rule to git client

.circleci/config.yml
- Cache without a lock file can have a negative impact (`npm i` will try to respect the cached modules instead of installing the latest)
- Updated the release context to use `lib` instead of `app` (more aligned to what this package is)
=> chore: circleci config improvements

lib/index.js, package.json, test/unit/predefine-pp-hotfix.test.ts
According to Snyk broker has a [Prototype Pollution vulnerability in predefine](https://snyk.io/vuln/SNYK-JS-PREDEFINE-1054935) package introduced via `primus@6.1.0 › fusing@1.0.0 › predefine@0.1.2`. Together with @ohad2712 we verified that no user input flows to the vulnerable function `merge` directly or indirectly. To be precise, we observed some user input flows to `merge` but only of type String – which makes it not exploitable.
To make double sure we decided to replace vulnerable implementation of the `merge` function with similar function `lodash.merge`, which is not vulnerable.
To replace the function we require `predefine` package as early as possible and replace the function by directly overwriting it.
`lib/index.js`
https://snyk.io/vuln/SNYK-JS-PREDEFINE-1054935
**predefine**: …
=> fix: replace vulnerable merge function of predefine package with not vulnerable lodash.merge implementation

.snyk
Ignore prototype pollution vulnerability in predefine introduced by `primus@6.1.0 > fusing@1.0.0 > predefine@0.1.2` because it fixed in https://github.com/snyk/broker/pull/336
https://github.com/snyk/broker/pull/336
https://github.com/snyk/broker/pull/336
=> fix: ignore prototype pollution vulnerability in predefine

lib/server/socket.js
Was introduced in https://github.com/snyk/broker/pull/326
Almost removed in https://github.com/snyk/broker/pull/340, so adding a comment to explain why this is there.
=> chore: add maxlength comment

lib/log.js, test/unit/log.test.ts
Add sanitisation to recently added env variables for Container integration.
It doesn't seem to be logged anywhere, but adding this just in case.
=> fix: sanitise CR env variables

client-templates/azure-repos/.env.sample
Add missing azure org parameter on git_url config
=> fix: azure repos - missing org context for git url

bin/container-registry-agent/docker-entrypoint.sh, test/bin/container-registry-agent/docker-entrypoint-test.sh
If a user sets `BROKER_CLIENT_VALIDATION_URL` then we also set
`BROKER_CLIENT_VALIDATION_AUTHORIZATION_HEADER` with whatever is in
CR_CREDENTIALS. The CRA will process the credentials in the systemcheck
endpoint.
=> feat: systemcheck for container integration

dockerfiles/artifactory/Dockerfile, dockerfiles/azure-repos/Dockerfile, dockerfiles/bitbucket-server/Dockerfile, dockerfiles/container-registry-agent/Dockerfile, dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile, dockerfiles/gitlab/Dockerfile, dockerfiles/jira/Dockerfile
To allow broker configuration by mounting a .env file.
If you do that today, those default ENV variables will override it. We should keep them only as comments.
=> feat: comment out default envvars in dockerfiles

client-templates/container-registry-agent/accept.json.sample
This PR removes endpoints that were added to replace the /api/v2/import/result and /api/v2/import/done, in an attempt to free the /v2 endpoint for the new Snyk API. Eventually, it has been decided to not break current functionality for customers, and therefore we do not use these endpoints.
Internal Slack thread: https://snyk.slack.com/archives/CBXS33GJY/p1621421246050600?thread_ts=1621363044.032300&cid=CBXS33GJY
=> fix: Remove unused container scan /v1 endpoints

client-templates/artifactory/.env.sample
RES_BODY_URL_SUB causes ERR_INVALID_ARG_TYPE errors because replaceUrlPartialChunk produces an 'object' for httpResponse.write, which is expecting a 'string' or 'Buffer'.
Removing this env var fixes the artifactory broker client image for non npm users (maven). A separate PR will fix replaceUrlPartialChunk so that this works in all scenarios.
=> fix: remove default RES_BODY_URL_SUB env var

lib/relay.js, test/functional/server-client.test.js
Fix bug replacing 'RES_BODY_URL_SUB' in relay.
The function returns an object with newChunk.
This should have been assigned to responseBody instead of the entire
object.
The effect of this was to transform our responses from a string to an object,
which when we attempt to write to the http response it throws 'ERR_INVALID_ARG_TYPE'.
Added 'RES_BODY_URL_SUB' env var to server-client functional test to
assert desired behaviour.
Without the fix to relay, you can now see the functional server-client test fail.
=> fix: replace partial chunk

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample
Extend accept.json of github.com and github-enterprise to allow Dockerfiles with a prefix and hidden (dot) dockerfiles (as done for other SCMs).
Create a file names `.dockerfile` in github/ghe and import it through a brokered connection.
This fix is done as part of adding support for fix PRs of hidden files and folders.
It is also related to the following PR created a few months ago: https://github.com/snyk/broker/pull/368
=> fix: Accept dockerfile with prefix in github and ghe

client-templates/azure-repos/accept.json.sample, lib/filters.js, test/fixtures/relay.json, test/unit/filters.test.ts
This change adds support for dot paths in the query filter, which allows importing hidden files and folders when the file path is specified in the query string. This is need in order to support importing hidden dockerfiles in azure repos, as well as opening a fixPR for these hidden files.
This fix is done as part of adding support for fix PRs of hidden files and folders.
=> feat: Add support for dot paths query filter

client-templates/nexus/.env.sample, client-templates/nexus/accept.json.sample, dockerfiles/nexus/Dockerfile, lib/log.js
- add Dockerfile and client-templates files for Nexus private repos
- compare with Artifactory structure
1 - BASIC CHECK - build the docker image to check it produces it correctly as a basic check, e.g. `docker build -t broker-nexus-client`
2 - BASIC CHECK - run `./dist/cli/index.js init nexus` (or `npm link` at the root to link the bin to the global bin dir so you can run   `broker init nexus` instead) -> check there are no errors and the Nexus `.env` and `accept.json` available in the root dir with the repo locally.
3 - FULL CHECK (run a container for Nexus broker client, Snyk broker server and a separate container to make requests to the broker server)
- Build the broker server image and run in a container. This requires just changing last line of `Dockerfile` to `CMD ["broker", …
=> feat: add setup for Nexus repositories

client-templates/nexus/.env.sample, client-templates/nexus/accept.json.sample
Reinstate the BASE_NEXUS_URL and adjust the accept.json to work for '/repository' and '/service/rest/v1/status/check'
- Reinstates the `BASE_NEXUS_URL` env var and makes an adjustment in the `accept.json` to account for `/repository` and `/service/rest/v1/status/check`
- can follow steps in https://github.com/snyk/broker/pull/382  (I also have it on my machine so can show you)
- reinstates things that were changed in https://github.com/snyk/broker/pull/388/files
- If we do go ahead with this, will need to make changes to pre-prod-broker-clients and reinstate `BASE_NEXUS_URL` in 1Password
=> fix: adjust Nexus env.sample and accept.json

lib/metrics.js, lib/relay.js, test/fixtures/client/filters.json, test/fixtures/server/filters.json, test/functional/metrics.test.ts, test/utils.ts
Introduces two new metrics:
* `broker_response_size_bytes`
* `broker_unable_to_size_response_count`
`broker_unable_to_size_response_count` can be removed if we see that all responses are being observed (this metric is empty).
`broker_response_size_bytes` starts at 1kb and goes upto the maximum length 20mb and is labeled with `isStreaming` (boolean).
=> feat: observe broker response size

lib/auth-header.js
Enables the possibility for broker client to use bearer tokens for auth.
Resolves: https://github.com/snyk/broker/issues/396
this is a copy of https://github.com/snyk/broker/pull/397
=>  feat: Add 'bearer' auth scheme #397 

lib/client/socket.js, lib/server/socket.js
- Ensures that websocket configuration parameters are of the expected type - previously these were set as `string`, which the underlying `primus` library may not correctly respect.
- Compare the types expected by `Primus` (https://github.com/primus/primus#getting-started) against the types specified in both `lib/client/socket.js` and `/lib/client/server.js`.
I've tested this by:
- Executing the project locally without any env vars to observe type of default configuration (logging the `io.options` object)
- Specifying environment variables (`SOCKET_MAX_RESPONSE_LENGTH="200000"`) and ensuring the value is updated in the `io.options` object, and that the type is correct (here, `Int`).
-
-
=> fix: correct websocket config types

lib/client/index.js
Adds the transport protocol to the `/healthcheck` endpoint payload.
1. Run the broker
2. Call `/healthcheck` endpoint
We have witnessed issues when the transport fails to upgrade and defaults to polling.  The issue is now solved, however, we want to make sure we can troubleshoot properly if this happens to any of the clients.
=> feat[NEBULA-550]: add tranport to healthcheck

lib/config.js, test/unit/config.test.ts
Stolen from: https://github.com/snyk/broker/pull/406
Addresses current environment variable substitution logic breaking passwords or any field that contains a $ character
lib/config.js lines 19/20
tests/unit/config.tests.js lines 6/13
enforce BITBUCKET_PASSWORD="abc$123" to be retained in config object after evaluate method
Very important to ensure users don't need to unnecessarily change their passwords and reduce security.
=> fix: env var substitution no removal of unmatched

dockerfiles/container-registry-agent/Dockerfile.ubi8
Fix cra: ubi8-based image to not include high-sev vuln.
This PR changes the way the container-registry-agent UBI image is built in order to create an image without high-severity vulns.
This is done by using a ubi8 base image and installing node from binary, which doesn't have the high severity vulns as the node version installed in `registry.access.redhat.com/ubi8/nodejs-16-minimal`
This work is aligned with the UBI image built for other broker clients.
The image was scanned locally with Snyk and no high severity vulns were found.
Build the image by running:
```
docker build . -f dockerfiles/container-registry-agent/Dockerfile.ubi8 -t <imagename>:<tag>
```
test the image by running:
```
snyk container test <imagename>:<tag>
```
=> chore: fix high-sev vulns in cra ubi8 base image

.snyk
This PR prolongs the predefine prototype pollution ignore as nothing has changed on [fusing](https://github.com/bigpipe/fusing ) since last year and no change is anticipated in the foreseeable future.
[#337](https://github.com/snyk/broker/pull/337)
=> fix: prolong prototype pollution predefine vulnerability snyk ignore

dockerfiles/ubuntu/Dockerfile
Updates the ubuntu base image to fix the permissions problem with openShift running by using a random user.
=> fix: run broker client on openshift

.editorconfig, README.md, lib/client/index.js, lib/config.js, lib/filters.js, lib/replace-vars.js, package.json, test/fixtures/client/filters.json, test/functional/server-client-pooled-credentials.test.js, test/functional/systemcheck.test.js, test/unit/config.test.ts, test/unit/replace-vars.test.ts
- [✅] Ready for review
- [✅] Follows [CONTRIBUTING](https://github.com/snyk/broker/blob/master/.github/CONTRIBUTING.md) rules
Users can now specify a credential pool by adding "_POOL" to the
environment variable name, and providing a comma-separated list of
credentials as the value, which will get turned into an array
internally. For example, to provide multiple GitHub tokens, you would
do:
GITHUB_TOKEN_POOL=token1, token2, token3, ...
This will then create an array, and anywhere that GITHUB_TOKEN is
referenced (e.g., in accept.json) it will instead pick a token from that
list (picking the first then second then third then back to the
beginning, etc).
It will also create an array of any other variables that reference it,
like BROKER_CLIENT_VALIDATION_AUTHORIZATION_HEADER - it will create …
=> feat: add ability to create a credential array

lib/relay.js
- Removes the header `content-encoding` from requests coming over the websocket connection
- When testing git cloning through the broker we found that git clone requests can add a 'content-encoding : gzip' header. As far as we know the broker does not support compressed payloads. As a result this causes requests to /git-upload-pack to be corrupted resulting in a clone error `fatal: error reading section header 'shallow-info'`. Removing the content-encoding header fixes this.
=> feat: remove content-encoding header from client requests

dockerfiles/artifactory/Dockerfile, dockerfiles/azure-repos/Dockerfile, dockerfiles/bitbucket-server/Dockerfile, dockerfiles/container-registry-agent/Dockerfile, dockerfiles/github-com/Dockerfile, dockerfiles/github-enterprise/Dockerfile, dockerfiles/gitlab/Dockerfile, dockerfiles/jira/Dockerfile, dockerfiles/nexus/Dockerfile, dockerfiles/nexus2/Dockerfile, dockerfiles/ubuntu/Dockerfile
OpenShift has very specific needs for permissions - all files should be part of the "root" group, and should have the same permissions as the primary user.
This needs to be done per-dockerfile so that can adjust permissions for all files, including those generated during the build.
Also remove global permissions from all files and folders while we're doing this.
- [✅] Ready for review
- [✅] Follows [CONTRIBUTING](https://github.com/snyk/broker/blob/master/.github/CONTRIBUTING.md) rules
Deploy any of the Broker Client docker images to OpenShift
[OpenShift Docs](https://docs.openshift.com/container-platform/4.9/openshift_images/create-images.html#images-create-guide-openshift_create-images) indicating this is the correct approach
=> fix: set permissions for OpenShift

lib/client/socket.js, lib/server/socket.js
- Allows the configuration of ping intervals and timeouts for the server and client
- The client values are defaulted to the [primus defaults](https://github.com/primus/primus/tree/6.1.0#connecting-from-the-browser)
- The server values and defaults had to be set at the [engine.io level ](https://github.com/socketio/engine.io/blob/917d1d29e13f2e8f523c3738f6413f67b587aebe/lib/server.ts#L138)as the the [Primus timeout option](https://github.com/primus/primus/tree/6.1.0#getting-started) did not have an effect on the socket ping interval or timeout
=> feat: set ping config through env

lib/relay.js, test/functional/server-client.test.js
Should really log errors as errors, but some "errors" aren't really errors. e.g., a 404 probably shouldn't be logged at all as they're very common, while a 502 from the Client should be logged at error level.
=> Log size of original request as well, and log errors as warnings

dockerfiles/ubuntu/Dockerfile
Ubuntu 22.04 has some issues with older versions of the Docker Engine in Kubernetes. It's not clear whether this is a bug in Ubuntu / the Ubuntu docker image, or if it's a bug in the Docker Engine. Either way, in order to retain support for older versions it is necessary to drop the Ubuntu version back down.
Symptoms of this include segfaults or hard-crashes with C/C++ stack traces, such as:
```
node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
1: 0xb02930 node::Abort() [node]
2: 0xb029ae [node]
3: 0xb6fb4e [node]
4: 0xb6fc16 node::NodePlatform::NodePlatform(int, v8::TracingController*) [node]
5: 0xac7d3d …
```
=> Drop Ubuntu version to 20.04

client-templates/bitbucket-server/accept.json.sample
This would allow us to create PRs with default reviewers assigned for Bitbucket Server. When you raise a PR via API, you need to do this manually.
The next section.
1. Run a `bitbucket-server` Broker image locally, and point it at either dev or local Broker Server. Use the new `accept.json` rules introduced in this PR.
2. Set up Bitbucket Server/Data Center integration with Broker, and point it at the local Broker set up in the previous step.
3. Create or update a repository with existing vulnerabilities in your Bitbucket Server/Data Center, and set a default reviewer for that repository. _NB! The default reviewer must be a user other than the one whose credentials are used to raise the PR._
4. Raise a fix PR on a repository imported from Bitbucket Server, and check if the PR has …
=> [ATLAS-67] feat: add default reviewers endpoint to BBS

client-templates/jira/accept.json.sample
Jira server version 9 deprecates calling `create-meta` with query parameters [https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html](). 
As such, we had to update our Jira integration to call the new endpoints as mentioned [here](https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#creating-an-issue-examples).
For this to work with the broker, this PR updates the `accept.json` example.
=> chore: add accept json rules for jira server version 9 api endpoints

lib/client/socket.js, lib/relay.js, lib/server/index.js, lib/stream-posts.js
Removed a callback that would handle the case where a response was emitted to a streaming request, which isn't supported. Unfortunately, this resulted in a substantial memory leak because the callback was never removed. This only affected the Broker Server, and then only if a large number of streaming requests were received.
Also added better handling for errors - e.g., destroying the stream to trigger proper error processing, and adding content-length/content-type for errors POST'd to the Server.
=> fix: remove callback that was causing memory leak

lib/relay.js, test/fixtures/client/filters.json, test/functional/client-server.test.js
Streaming requests received from the Client were not being handled correctly (the server was attempting to POST the response to the client), which was causing the Server to crash. In general, this seems like a configuration error on the Client side, but it is happening in production so needed to be fixed.
This has been fixed and responses will be correctly sent to the Client.
=> fix: Server was encountering an error when streaming was requested from Client

README.md, lib/filter-rules-loading.js, test/unit/runtime-rules-hotloading.test.ts
Fixes the trigger mechanism for ACCEPT_IAC and ACCEPT_CODE rule injection to actually run.
ACCEPT env var is used all the time, so custom accept files are loaded if not pointing to the default accept.json. Using this value as baseline to detect custom accept json file loading, and skipping rule injection in this case only.
=> fix: correct triggering mechanism for iac and code rule injection

lib/relay.js, package.json, test/functional/server-client.test.js, test/unit/relay-response-body.test.ts
As some backend systems (e.g., Nexus) use these headers in unexpected ways, it is safer for us to strip out any header starting with X-Forwarded-, along with the Forwarded header.
Configurable via the REMOVE_X_FORWARDED_HEADERS, so it can be turned off if there are any unexpected issues.
=> Add environment variable to strip all X-Forwarded-* headers

client-templates/container-registry-agent/accept.json.sample
Adds missing rules to support Snyk general move to api.DOMAIN, removing the /api from the path for CRA usage.
=> fix: add missing rules for CRA endpoints using api hosts

dockerfiles/container-registry-agent/Dockerfile
This PR bumps Node.js version to 18 (latest LTS) for CRA image to fix high vulnerabilities.
=> fix(cra): bump node version to 18 lts

dockerfiles/base/Dockerfile.ubi
This PR removes some non-needed packages from RHEL UBI base image and reduces vulnerability risk. Following packages are removed:
- libssh
- libssh-config
- libtasn1
- libxml2
- lz4-libs
- ncurses-base
- openldap
- gpg
- python-pip-wheel
=> fix(docker): remove non-needed packages from RHEL UBI image

lib/common/relay/forwardHttpRequest.ts
Adds a specific line of logs to include the streamingID in the brokered requests to help with end to end request tracking in logs.
=> fix: add streaming id in logging [HYB-231]

dockerfiles/base/Dockerfile, dockerfiles/base/Dockerfile.ubi, package.json
This PR removes `tough-cookie` version pinning. Since `request` package was removed in version [4.166.0](https://github.com/snyk/broker/releases/tag/v4.166.0), we don't need it anymore.
=> fix(docker): remove tough-cookie dependency pinning [HYB-123]

lib/client/checks/http/index.ts, lib/client/index.ts, lib/client/routesHandler/healthcheckHandler.ts, lib/client/utils/socketHelpers.ts, lib/common/relay/forwardHttpRequestOverHttp.ts, test/fixtures/client/filters-webhook.json, test/fixtures/server/filters-webhook.json, test/fixtures/webhook/payload.json, test/functional/webhook.test.ts, test/setup/test-web-server.ts, test/unit/client/checks/check.test.ts
Adds a fallback mechanism for webhook events to be relayed via HTTPS to the API in case the WS tunnel is down for any reason.
=> feat: add fallback api route for webhook if ws conn down [HYB-448]

lib/common/http/downstream-post-stream-to-server.ts
Reverts to previous error handling to avoid uncaught exception. Also doesn't make sense to send the error over the connection.
=> fix: revert handle error to previous

lib/common/relay/prepareRequest.ts, test/unit/relay-response-body-universal.test.ts, test/unit/relay-response-headers-universal.test.ts
Fixes broker var substitution in body and header for universal mode.
The expected variable to be replacing the body/header placeholders need to live under the corresponding connection.
=> fix: body and header var sub in universal mode

lib/common/http/downstream-post-stream-to-server.ts
Pushes the error message in the buffer final message, a string, instead of the error type, causing a crash.
=> fix: avoid crashed on econnresets

lib/common/config/config.ts, test/unit/relay-response-body-universal.test.ts
Replace env var placeholders in string, not just for "mirroring" env vars alone.
=> fix: make env var replace in string

lib/common/config/universal.ts, test/unit/config.test.ts
Returns a config for a given identifier with the whole set of variables (default+inputted) replacing all placeholders to be ready for use.
=> fix: get consolidated cfg for id with replaced env vars

lib/common/relay/forwardHttpRequest.ts
Removing stream flag causing some websocket flow to be misdirected, causing "Trying to write into a close stream" message.
=> fix: avoid inbound ws to be routed wrongly

config.universaltest3.json, lib/client/hooks/startup/processHooks.ts, lib/client/routesHandler/websocketConnectionMiddlewares.ts, test/fixtures/client/filters-webhook.json, test/functional/webhook-universal.test.ts, test/setup/test-web-server.ts
Handle universal webhook connection selection more tightly and handle the ghe connections receiving /webhooks/github/UUID calls, therefore not matching github-enterprise type available. Smarter selection will now use the github-enterprise selection in this type of situations.
=> fix: handle gh ghe webhooks in universal broker [HYB-261]

lib/common/relay/forwardWebsocketRequest.ts
Fix wrong conditional order for log info.
=> fix: align info log client vs server

defaultFilters/apprisk.json, lib/common/relay/prepareRequest.ts, test/functional/server-client.test.ts, test/unit/relay-response-body-form-url-encoded.test.ts, test/unit/relay-response-body-universal-form-url-encoded.test.ts, test/unit/relay-response-headers-form-url-headers.test.ts, test/unit/relay-response-headers-universal-form-url-headers.test.ts
1. fixing content-type header ducplications
2. remove BROKER_VAR_SUB from the request 
after the broker is replacing the variables we dont need the BROKER_VAR_SUB anymore
3. fixing Content length calculation after converting body to query search params
=> fix: url encoded header fix

dockerfiles/Dockerfile.ubi, dockerfiles/base/Dockerfile.ubi
This PR sets `WORKDIR` for rhel-ubi images and ensures that accept filter and all related files are copied into the `/home/snyk` folder.
In the previous images `accept.json` was created under root `/` and defaultFilters and config.default.json under `home/node`, so rules injection with `ACCEPT_*` flags didn't work.
=> fix(docker): set workdir for rhe-ubi docker images

defaultFilters/apprisk/azure-repos.json, defaultFilters/apprisk/github.json, defaultFilters/apprisk/gitlab.json, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap
This is a follow-up to https://github.com/snyk/broker/pull/748, which adds the `catalog-info.yaml` file for other SCMs.
N/A
N/A
N/A
N/A
N/A
=> feat: add catalog-info.yaml paths for azure, github, gitlab

lib/client/checks/config/customAcceptFile.ts, lib/client/checks/config/index.ts, test/unit/client/checks/config/acceptFlagsConfigCheck.test.ts
Signals ACCEPT flags incompatibility and report code agent deprecation as per our [Code Agent docs](https://docs.snyk.io/enterprise-configuration/snyk-broker/snyk-broker-code-agent)
=> fix: add accept cfg preflight checks signaling codeagent deprec [HYB-437]

lib/client/checks/config/codeAgentDeprecation.ts, lib/client/checks/config/index.ts, test/unit/client/checks/config/codeAgentDeprecation.test.ts
Officially deprecate code agent usage in clients.
=> fix: add code agent deprecation preflight check [HYB-437]

.circleci/config.yml, .snyk, dockerfiles/base/Dockerfile.ubi
This PR ignores `SNYK-RHEL8-GLIBC-6656573` and `SNYK-RHEL8-GLIBC-6684409` for one week (until 2024-05-14) and unblocks failed workflow for releasing RHEL UBI images.
Additionally old ignores from `.snyk` policy file are cleaned up.
=> fix: gnore glibc vuln for UBI images

dockerfiles/base/Dockerfile.ubi
This PR removes additional packages from RHEL UBI image (coming from latest ubi8 image)
- glibc-gconv-extra
- glibc-langpack-en
=> fix(docker): remove non-needed glibc-* packages

lib/client/checks/config/brokerClientVersionCheck.ts, test/unit/client/checks/config/brokerClientVersionCheck.test.ts, test/unit/client/checks/config/brokerClientVersionSkipDevLocalVersionCheck.test.ts
Fixes the way we retrieve version.
=> fix: version retrieval in preflight check

lib/server/routesHandlers/httpRequestHandler.ts, test/unit/old-client-redirect.test.ts
Makes sure to target the right endpoint for request being forwarded from secondary to primary for older client with only one tunnel.
=> fix: secondary to primary calls to right endpoint

lib/server/routesHandlers/httpRequestHandler.ts, test/functional/server-client.test.ts, test/unit/old-client-redirect.test.ts
[Server only] Strips connection_role query string on inbound request from backend systems to not forward it to downstream services.
=> fix: strip connection_role qs in http req into server

lib/server/routesHandlers/connectionStatusHandler.ts, test/unit/old-client-redirect.test.ts
Forwards request for connection-status routes from secondary to primary broker server for older client without double tunnels primary and secondary.
=> fix: apply old clients fwding to primary for conn status routes [HYB-535]

dockerfiles/Dockerfile.ubi, dockerfiles/base/Dockerfile.ubi
- Sets directories `/home/snyk` and contents within to be owned by the `snyk` user and the `root` group
=> fix: dynamic gids for openshift for rhel-ubi

dockerfiles/base/Dockerfile.ubi
- Move from `yum` to `dnf`
- Ignore weak dependencies when building base image
- Reduce additional packages, limiting surface for vulnerabilities
=> fix: do not install weak deps

lib/server/routesHandlers/httpRequestHandler.ts
[Server only] Interrupts code flow upon error in secondary to primary request forwarding instead of continuing after having returned 500 error code.
Server side only. No impact or change required on deployed broker clients.
=> fix: [server only] stop secondary to primary fwd flow on err [HYB-512]

lib/common/relay/prepareRequest.ts
Sets the content length calculation after the git commit signing, which was placed wrong during refactoring.
=> fix: content length set after commit signing

lib/common/relay/prepareRequest.ts, test/unit/relay-response-body-universal-form-url-encoded.test.ts, test/unit/relay-response-body.test.ts
- Ensures the `Content-Length` header uses bytes
- Ensures `Content-Length` format is standardised to `Content-Length`
=> fix: ensure content length uses bytes

.snyk, lib/common/http/webserver.ts
Mitigates SNYK-JS-WS-7266574.
Bumping ws requires bumping all primus deps, which can't be done at this time (primus heartbeat mechanism reverses after current version, requiring tight alignement broker client <-> broker server).
Migration will be carried out at a later time once fully on universal broker stack control and version based routing will be introduced.
=> fix: mitigate vuln SNYK-JS-WS-7266574

defaultFilters/github-server-app.json
Undo #807 for backwards compatibility.
=> chore: undo webhook path update for github-server-app - use github in path

client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/github-server-app/accept.json.sample, defaultFilters/github-enterprise.json, defaultFilters/github-server-app.json, defaultFilters/github.json, test/fixtures/accept/github.json, test/fixtures/client/github/graphql/find-pull-request-threads.txt, test/fixtures/client/github/graphql/resolve-pull-request-thread.txt, test/fixtures/relay.json, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap, test/unit/filters.test.ts
Adds the ability to allow native PR experience calls through the Broker, to manage general comments, create reviews and resolve review threads in GitHub.
=> feat: allow GitHub native PR experience calls through the Broker

lib/client/config/remoteConfig.ts, test/unit/remoteConfig.test.ts
Updates the endpoint from which the universal broker retrieves the connections details. Simplifies the parameters to pass to the broker client in the deployment/container.
=> fix: update remote cfg url for unibroker

dockerfiles/base/Dockerfile.ubi
Removes unused libyaml in UBI image.
https://access.redhat.com/security/cve/CVE-2024-35325
=> fix: rm CVE-2024-35325

client-templates/bitbucket-server-bearer-auth/accept.json.sample, client-templates/bitbucket-server/accept.json.sample, defaultFilters/bitbucket-server-bearer-auth.json, defaultFilters/bitbucket-server.json, test/fixtures/accept/bitbucket-server-bearer-auth.json, test/fixtures/accept/bitbucket-server.json, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap, test/unit/filters.test.ts
Adds rules for bitbucket server general comments
- https://github.com/snyk/bitbucket-server-agent/pull/616
- https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#idm8288072528
=> feat: add bitbucket server general comment rules [SCM-516]

.pre-commit-config.yaml, lib/client/brokerClientPlugins/abstractBrokerPlugin.ts, test/fixtures/plugins/dummy-multi.js, test/unit/plugins/pluginManager.test.ts
- Adjusts the enablement mechanism for plugins to load if one or more of the defined `applicableBrokerTypes` are present in config
- Previously _all_ matching broker types must be present
=> fix: allow one or more matching connection types for plugin enablement

dockerfiles/base/Dockerfile.ubi
Remove libexpat from expat package, unused by Broker, but reported as "vuln" (https://nvd.nist.gov/vuln/detail/CVE-2024-45490, https://nvd.nist.gov/vuln/detail/CVE-2024-45491, https://nvd.nist.gov/vuln/detail/CVE-2024-45492) in some scanners.
=> chore: rm expat from rhel image to reduce vuln FP

.circleci/config.yml
Adds missing apprisk flavor in classic broker (non universal broker).
This apprisk flavor is different from the ACCEPT_APPRISK which enables apprisk over connections to SCM, possibly used for other Snyk flows.
This apprisk image supports specifically connectivity to third party system specifically for Snyk Apprisk products.
=> feat: add apprisk docker images releases

.releaserc
Fixes release process to release following:
Adds missing apprisk flavor in classic broker (non universal broker).
This apprisk flavor is different from the ACCEPT_APPRISK which enables apprisk over connections to SCM, possibly used for other Snyk flows.
This apprisk image supports specifically connectivity to third party system specifically for Snyk Apprisk products.
=> fix: release process ensuring sboms folder exists

lib/common/relay/forwardWebsocketRequest.ts, test/functional/client-server.test.ts, test/functional/webhook.test.ts, test/setup/test-web-server.ts
Adds x-snyk-broker header in client->server side requests.
=> chore: add server side broker header

.circleci/config.yml, .circleci/templates/slack_fail_message.json, .snyk
This PR adds "Scan base images" job for Ubuntu and RHEL images during CICD CircleCI workflow. This will allow to catch vulnerability issues before releasing to NPM.
Additionally
- CircleCI failed message template is moved under `.circleci/template/slack_fail_message.json` for better readability in config.yml
- Skip monitoring of broker project during Snyk scans in CICD workflow (otherwise we update project snapshot by each PR)
- ignore pam vulnerability in RHEL UBI image temporary (this unblocks releasing of UBI images)
=> chore: scan broker images as part of cicd workflow

.circleci/config.yml, dockerfiles/base/Dockerfile
This PR upgrades base image to `ubuntu:24.04` for nlatest versions, so we can test it before upgrade for stable versions.
Additionally Node.js version for nlatest is bumped to 23.
Please note, that from `ubuntu:24.04` a ubuntu user with uid 1000 is already included in the image (https://bugs.launchpad.net/cloud-images/+bug/2005129). That's why we pass user uid and gid via build arguments and default value 1000 (as it was in ubuntu:20.04).
=> feat: upgrade nlatest base image to ubuntu:24.04

lib/server/routesHandlers/postResponseHandler.ts, test/fixtures/client/filters.json, test/functional/server-client.test.ts, test/setup/test-web-server.ts
Handles non ascii characters in headers gracefully by calculating the length appropriately instead of relying on .length.
=> fix: handle non ascii chars in headers [HYB-778]

dockerfiles/base/Dockerfile
This PR adds a new Node.js release GPG key, so builds for Node.js 23 (nlatest) works as expected.
=> fix: add missing node.js release gpg key

lib/client/config/configHelpers.ts, test/unit/configHelper.test.ts
Make the config metadata accurately reflect reality, accounting for classic broker having accept value set to accept.json, therefore not custom, reporting it wrongly as custom json usage.
=> fix: make custom accept cfg metadata accurate

client-templates/bitbucket-server/.env.sample, config.default.json, lib/common/filter/filter-rules-loading.ts, test/unit/__snapshots__/runtime-rules-hotloading.test.ts.snap
Adds a local override to be able to use a separate git endpoint for custom bitbucket configurations that require it.
=> feat: add local override for separate bitbucket-server git endpt

defaultFilters/apprisk/gitlab.json
This PR is to solve errors that gitlab clients are getting. Example of these clients are [here](https://snyksec.atlassian.net/browse/IA-872). The issue is related to the fact that a step in sanity checks in apprisk are failing with the following error:
{ "message": "blocked", "reason": "[Websocket Flow][Blocked Request] Does not match any accept rule", "url": "/api/v4/projects/20263346/users" }
=> chore: add apprisk gitlab whitelist

lib/client/checks/config/brokerClientUrlCheck.ts, lib/client/checks/config/brokerServerUrlCheck.ts, lib/common/utils/urlValidator.ts, test/unit/client/checks/config/brokerServerUrlCheck.test.ts
- Adds a preflight check for BROKER_SERVER_URL
- Ensure the URL contains a schema (`http[s]://`)
=> chore: add broker-server-url preflight check

client-templates/bitbucket-server-bearer-auth/accept.json.sample, client-templates/bitbucket-server/accept.json.sample, client-templates/gitlab/accept.json.sample, defaultFilters/bitbucket-server-bearer-auth.json, defaultFilters/bitbucket-server.json, defaultFilters/gitlab.json, test/unit/filters.test.ts
Adds rules for Gitlab and Bitbucket Server to facilitate updating webhooks.
https://github.com/snyk/bitbucket-server-agent/pull/686
https://github.com/snyk/gitlab-agent/pull/764
=> feat: add gitlab and bitbucket server update hook rules

client-templates/bitbucket-server-bearer-auth/.env.sample, config.default.json
Adds BITBUCKET_GIT, recently added as a way to possibly override the git endpoint if a custom one is used. This addition made it into the filters but we missed adding the default value in the bearer auth .env file.
=> fix: add missing bitbucket server git env var for bearer auth connections

client-templates/azure-repos/accept.json.sample, client-templates/github-com/accept.json.sample, client-templates/github-enterprise/accept.json.sample, client-templates/github-server-app/accept.json.sample, defaultFilters/azure-repos.json, defaultFilters/github-enterprise.json, defaultFilters/github-server-app.json, defaultFilters/github.json, test/fixtures/accept/github.json
Adds filter rules to allow Github and Azure Repos API calls to enable upgrading subscribed webhook events.
https://github.com/snyk/scm-agents/pull/647
https://github.com/snyk/azure-repos-agent/pull/627
=> fix: add github and azure-repos filter rules for webhook event upgrades

defaultFilters/apprisk/github.json
Whitelist github url for custom properties that are attached to repos.
Jira: https://snyksec.atlassian.net/browse/IA-809
=> chore: add github apprisk endpoint to whitelist

lib/hybrid-sdk/client/connectionsManager/manager.ts, lib/hybrid-sdk/client/index.ts, lib/hybrid-sdk/common/utils/signals.ts, lib/hybrid-sdk/server/socketHandlers/closeHandler.ts, lib/hybrid-sdk/server/socketHandlers/connectionHandler.ts, lib/hybrid-sdk/server/socketHandlers/identifyHandler.ts, lib/hybrid-sdk/server/socketHandlers/terminateHandler.ts, test/functional/server-client-universal-termination-signal.test.ts
Adds graceful client shutdown with advanced shutdown signaling to the server which can then signal upcoming client connection shutdown to the load balancing system.
It's a no-op for normal broker behavior. The rest requires the entire stack.
=> chore: add graceful client shutdown with signaling to server [HYB-866]

.circleci/config.yml, lib/hybrid-sdk/clientRequestHelpers.ts, lib/hybrid-sdk/http/request.ts, lib/hybrid-sdk/server/routesHandlers/authHandlers.ts, lib/hybrid-sdk/server/routesHandlers/connectionStatusHandler.ts, lib/hybrid-sdk/server/routesHandlers/httpRequestHandler.ts, lib/hybrid-sdk/server/socket.ts
This PR includes Snyk Security Scan into CICD pipeline (not only for Deploy). On non-released branches it will run `snyk test` and on released branches it will run `snyk monitor` command.
=> chore: add security_scans into CICD pipeline

.circleci/config.yml
This PR uses hybrid (instead of broker) org for security scans.
The release-branch parameter for security_scans is adjusted, to enable `snyk monitor` command on broker releases.
=> chore: use correct circleci context for security scans

client-templates/azure-repos/accept.json.sample, client-templates/gitlab/accept.json.sample, defaultFilters/azure-repos.json, defaultFilters/gitlab.json, test/unit/filters.testskip.ts
Adds the ability to allow native PR experience calls through the Broker, to manage general comments, create discussions and resolve discussions in Azure Repos.
=> chore: allow native pr experience azure repos and gitlab

test/unit/filters-and-interpolates.test.ts
Cleans things up post refactoring and introduces again the tests to verify the now refactored filter function into filter+interpolate.
Filter now only filters, returning false or the matching rule.
The interpolation part has been refactored out.
npm run test.
=> chore: adding filtering and interpolate tests post refac

client-templates/azure-repos/accept.json.sample, defaultFilters/azure-repos.json, test/unit/filters-and-interpolates.test.ts
Fixes the Azure Repos filtering rules for Native PR Experience - adds the missing `/:owner` prefix to the API endpoints.
In addition, this PR removes a duplicate from the Native PR Experience filter rules.
Fixes a bug introduced in #946 where the API calls for Native PR Experience flows failed due to the missing repo owner prefix.
=> fix: azure repos npx rules

lib/hybrid-sdk/client/dispatcher/client/api.ts, lib/hybrid-sdk/client/dispatcher/index.ts, test/functional/dispatcher-client-api.test.ts
- [] Follows [CONTRIBUTING](https://github.com/snyk/broker/blob/master/.github/CONTRIBUTING.md) rules
Add return code on dispatcher backoff info messages in logs for easier troubleshooting.
Goal is to provide better clarity as to why the dispatcher is backing off.
=> chore: add return code on dispatcher retry info

.snyk
This PR ignores [the vulnerability](https://security.snyk.io/vuln/SNYK-RHEL8-KRB5LIBS-9620338) for RHEL-UBI8 images. It was published on 2 April 2025, there is no fix from RHEL available yet.
=> fix: ignore vuln in rhel-ubi8 image temporarily

.circleci/config.yml
Put the image building approval steps on releases, on tags and not dev branches.
=> fix: make approval steps work on tags

lib/hybrid-sdk/client/brokerClientPlugins/abstractBrokerPlugin.ts, lib/hybrid-sdk/client/brokerClientPlugins/plugins/githubServerAppAuth.ts, lib/hybrid-sdk/common/config/pluginsConfig.ts, test/unit/plugins/brokerPlugins/github-server-app.test.ts
Refactors memory access for plugins to make it easier to access and more readable.
=> chore: refactor pluginconfig access

lib/broker-workload/websocketRequests.ts, lib/hybrid-sdk/client/brokerClientPlugins/abstractBrokerPlugin.ts, lib/hybrid-sdk/client/brokerClientPlugins/pluginManager.ts, lib/hybrid-sdk/client/brokerClientPlugins/plugins/containerRegistryCredentialsFormatting.ts, lib/hybrid-sdk/client/brokerClientPlugins/plugins/githubServerAppAuth.ts, test/fixtures/plugins/dummy-context.js, test/unit/plugins/pluginManager.test.ts
Adds context support in plugins manager.
The contexts are section under a connection in the connections object retrieved from the backend.
The plugin abstract class brings a new startup context method which plugins must implement, giving the opportunity to mutate the configuration just like the regular startup method, but for each context independently.
Using this startupContext method, each context configuration can be mutated to contain whatever updated field/value. The allowed values will likely need tweaking but will be addressed in a separate PR.
Each context object under the given connection will contain the values set by plugins.
The prerequest method, if used/called, will remain largely unchanged, but will get a configuration object containing overriden values by the context …
=> feat: add context support to plugins manager [HYB-980]

lib/hybrid-sdk/common/filter/filter-rules-loading.ts, test/functional/server-client-universal-termination-signal.test.ts, test/functional/server-client-universal.test.ts
Prepends the injected rules for essentials and custom pr templates in the filters lists to have them evaluated first.
The injected rules tends to be more restrictive than others. Being evaluated first allows to avoid some issues in some corner cases where other more permissive filters are a match before the actual targeted rule.
This PR fixes corner cases like where a repo called something containing "dockerfile" would not be functional for repos/:org/:repos/languages as another rule with *Dockerfile would catch it prior, injecting different origin scheme.
=> fix: add injected rules to be evaluated first

.vscode/launch.json
Adds `.vscode/launch.json` config for debugging tests with jest and also running the universal broker locally.
=> chore: add launch.json for vscode debugging

.snyk, client-templates/gitlab/accept.json.sample, defaultFilters/gitlab.json, test/unit/filters-and-interpolates.test.ts
Allows the retrieval of MR changes/diffs in Gitlab by allowing the `/api/v4/projects/:project/merge_requests/:pullRef/diffs` endpoint. This can be used to help determine which lines in a Gitlab MR can be commented on, since Gitlab does not allow commenting outside the diff of a MR.
=> chore: allow gitlab mr diffs

defaultFilters/bitbucket-server-bearer-auth.json, defaultFilters/bitbucket-server.json
Adds a copy of existing broker rules with missing `/rest/api/1.0` for comment routes.
I've yet to confirm if these routes are necessary, but in the interest of time-to-fix, this will add the missing prefixes separately, and I'll follow up to cleanup the old rules.
=> fix: add rest prefix to a copy of existing suspect bitbucket-server-agent rules [SCM-1313][ARI-987]

defaultFilters/apprisk/gitlab.json
Allows files called backstage-caytalog-info.yaml to be downloaded when using a broker with gitlab. Previously allowed catalog-info.yaml
https://snyk.slack.com/archives/C04B9B08G2G/p1748437195315419
this endpoint uses /raw in the end so there is no other rule
=> chore(gitlab): allow backstage-catalog-info.yaml

.snyk, package-lock.json, package.json
- Upgrades axios to `1.11.0`
- Resolve https://security.snyk.io/vuln/SNYK-JS-FORMDATA-10841150
- CI appears to fail due to an unrelated vulnerability in the underlying RHEL image
=> fix: update axios to resolve form-data vuln

client-templates/bitbucket-server-bearer-auth/accept.json.sample, client-templates/bitbucket-server/accept.json.sample, defaultFilters/bitbucket-server-bearer-auth.json, defaultFilters/bitbucket-server.json, test/unit/filters-and-interpolates.test.ts
adds rules to support repository based commit statuses for bitbucket server
https://developer.atlassian.com/server/bitbucket/reference/api-changelog/#new-rich-build-status
=> feat: add repository based commit status rules for bitbucket server

.circleci/config.yml
Support for Ubuntu:24.10 ended on 10. July 2025. This PR updates the Ubuntu for edge images to 25.04.
Support matrix: https://endoflife.date/ubuntu
=> fix(circleci): use ubuntu:25.04 for edge images
